fix clear copyset creating flag when create copyset success
opencurve/curve pull request #1417
Opened 2022-05-10 09:02 UTC by cw123

### What problem does this PR solve?

Issue Number: #1382

Problem Summary: Copyset is not automatically migrated after stopping metaserver

### What is changed and how it works?

What's Changed: fix clear copyset creating flag when create copyset success

When copyset created success, it should clear the copyset creating flag. But the code miss this in code.

2022-05-11 02:23 UTC, cw123 commented
recheck

2022-05-11 06:19 UTC, cw123 commented
recheck

2022-05-11 09:17 UTC, YunhuiChen commented
recheck

2022-05-12 07:12 UTC, Wine93 requested changes
LGTM!

2022-05-12 07:13 UTC, Wine93 approved these changes
LGTM!

2022-05-12 07:15 UTC, wu-hanqing commented on curvefs/src/mds/topology/topology_manager.cpp
> +    ClearCopysetCreating(copyset.poolId, copyset.copysetId);
it's better to move this line of code before 856 and remove line 865, so you don't have to repeat it.

and should you add some unit test?

2022-05-12 07:41 UTC, cw123 commented on curvefs/src/mds/topology/topology_manager.cpp
> +    ClearCopysetCreating(copyset.poolId, copyset.copysetId);
虽然都是去掉creating的标记，但是清理的时机是不一样的。如果都挪到856行，和原意还是有区别的。

Although the marking of creating is removed, the timing of cleaning is different. If it is moved to line 856, it is still different from the original intention.

2022-05-12 08:53 UTC, wu-hanqing approved these changes

2022-05-12 11:34 UTC, merged