【translate】mds/schedule
opencurve/curve pull request #142
Opened 2020-10-29 01:59 UTC by SeanHai

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

2020-11-11 03:17 UTC, cw123 requested changes

2020-11-13 09:15 UTC, SeanHai commented on src/mds/schedule/coordinator.cpp
> +    // Iterate whether each chunkserver is recovering
> 查询拼错了

done

2020-11-13 09:19 UTC, SeanHai commented on src/mds/schedule/coordinator.h
> +     * @param[in] flag
> 没有翻译

上面brief中已经描述了。
     * @brief SetScheduleRunning Stop all the schedulers if set to false
     *
     * @param[in] flag

2020-11-14 04:59 UTC, SeanHai commented on src/mds/schedule/copySetScheduler.cpp
> +     *    condition: range and average volume fall into a certain percentage
> 条件：极差超过均值的百分比范围，开始迁移

done

2020-11-14 05:12 UTC, SeanHai commented on src/mds/schedule/leaderScheduler.cpp
> +            // can not be the leader
> 翻译意思好像不对

done

2020-11-14 05:14 UTC, SeanHai commented on src/mds/schedule/recoverScheduler.cpp
> +        // do nothing if all replicas are offline
> 意思反了

done

2020-11-14 05:14 UTC, SeanHai commented on src/mds/schedule/recoverScheduler.cpp
> +        // recover onr of the offline replica
> one

done

2020-11-14 05:46 UTC, SeanHai commented on src/mds/schedule/scheduler.h
> +     * @return kScheduleErrCodeSuccess
> return 的意思

done

2020-11-14 05:51 UTC, SeanHai commented on src/mds/schedule/scheduler_helper.cpp
> +    // the newValue falls inside [min, max]
> 这里的注释应该有问题，这个时候，newValue可能还有在[min, max]之外

delete

2020-11-14 12:53 UTC, SeanHai commented on src/mds/schedule/scheduler_helper.cpp
> + *     (newValue-oldValue<=-1)
> 加上if条件

done

2020-11-14 12:55 UTC, SeanHai commented on src/mds/schedule/scheduler_helper.cpp
> + *     (newValue-oldValue<=0)
> 加上if条件

done

2020-11-18 06:46 UTC, cw123 approved these changes

2020-11-18 06:46 UTC, cw123 approved these changes

2020-11-18 07:23 UTC, ilixiaocui approved these changes

2020-11-18 07:24 UTC, merged