client read not allocate segment
opencurve/curve pull request #172
Opened 2020-11-26 03:06 UTC by SeanHai

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

2020-11-26 06:54 UTC, wu-hanqing requested changes
再添加一下相关场景的单元测试吧。

2020-11-26 06:54 UTC, wu-hanqing commented on src/client/io_tracker.cpp
> +        int ret = curveClient->AioRead(fd, &curveCombineCtx->curveCtx);
这个调用少了一个参数吧？

2020-11-26 06:54 UTC, wu-hanqing commented on src/client/io_tracker.cpp
> +                    zeroDataBuf.append(zeroData);
IOBuf直接有一个resize的接口，可以直接用。

2020-11-26 06:54 UTC, wu-hanqing commented on src/client/io_tracker.cpp
> +            if(0 == r->idinfo_.lpid_ && 0 == r->idinfo_.cpid_
这个判断可以封装一下，或者直接用ChunkIDInfo::Valid？再确认一下，正常情况下chunkid、copysetid、logicalpoolid会不会等于0

2020-11-26 06:54 UTC, wu-hanqing commented on src/client/io_tracker.cpp
> +                    readDatas_[r->subIoIndex_] = zeroDataBuf;
这里r->subIoIndex_还没赋值吧？

2020-11-26 06:54 UTC, wu-hanqing commented on src/client/io_tracker.cpp
> +        ret = ReadFromOrigin(originReadVec, fileInfo->userinfo);
这里会把上一步返回的值给覆盖掉

2020-11-26 06:54 UTC, wu-hanqing commented on src/client/io_tracker.cpp
> +            auto iter = fdMap_.find(fileName);
IOTracker是跟踪一个用户IO请求的，fdMap_放IOTracker内部，每次都是空的。
可以考虑放到FileClient4ReadClone里面去。

而且需要添加一下，定期关闭一直没有IO的卷。

2020-11-26 07:49 UTC, SeanHai commented on src/client/io_tracker.cpp
> +                    readDatas_[r->subIoIndex_] = zeroDataBuf;
> 这里r->subIoIndex_还没赋值吧？

改为readDatas_[subIoIndex_] = zeroDataBuf;

2020-11-26 07:49 UTC, SeanHai commented on src/client/io_tracker.cpp
> +                    zeroDataBuf.append(zeroData);
> IOBuf直接有一个resize的接口，可以直接用。

改为：
butil::IOBuf zeroDataBuf;
zeroDataBuf.resize(r->rawlength_, 0);

2020-11-26 07:50 UTC, SeanHai commented on src/client/io_tracker.cpp
> +        int ret = curveClient->AioRead(fd, &curveCombineCtx->curveCtx);
> 这个调用少了一个参数吧？

改为：
int ret = curveClient->AioRead(fd, &curveCombineCtx->curveCtx, UserDataType_);

2020-11-26 07:57 UTC, SeanHai commented on src/client/io_tracker.cpp
> +        ret = ReadFromOrigin(originReadVec, fileInfo->userinfo);
> 这里会把上一步返回的值给覆盖掉

改为：
ret = scheduler_->ScheduleRequest(reqlist_);
ret += ReadFromOrigin(originReadVec, fileInfo->userinfo);
...
if (ret < 0) {
   LOG(ERROR) << "split or schedule failed, return and recycle resource!";
    ReturnOnFail();
}

2020-11-26 09:35 UTC, SeanHai commented on src/client/io_tracker.cpp
> +            if(0 == r->idinfo_.lpid_ && 0 == r->idinfo_.cpid_
> 这个判断可以封装一下，或者直接用ChunkIDInfo::Valid？再确认一下，正常情况下chunkid、copysetid、logicalpoolid会不会等于0

改为：
ChunKIDInfo中新增 字段    bool chunkExist = true; 标记chunk不存在时添加到metaChache中的特殊ChunkIdInfo

2020-12-14 07:46 UTC, bai-charisu commented on src/client/io_tracker.cpp
> +    done->SetFailed(LIBCURVE_ERROR::OK);
上面SetFailed成FAILED之后，这里又Set成OK？？

2020-12-14 07:46 UTC, bai-charisu commented on test/client/fake/mock_schedule.cpp
> +    // LOG(ERROR) << size;
为啥注释掉？

2020-12-14 07:46 UTC, bai-charisu commented on test/client/fake/mock_schedule.cpp
> +       // if (processed >= size) {
为啥注释掉？

2020-12-14 07:46 UTC, bai-charisu commented on test/client/iotracker_splitor_unittest.cpp
> +       // for (auto iter : sinfo.chunkvec) {
为啥注释掉？

2020-12-14 07:46 UTC, bai-charisu commented on test/client/iotracker_splitor_unittest.cpp
> +    ASSERT_EQ(0, data[4 * 1024 - 1]);
这几个断言是为了断言data是全0的吗？可以写在循环里

2020-12-14 07:46 UTC, bai-charisu commented on test/client/iotracker_splitor_unittest.cpp
> +    ASSERT_EQ('a', data[4 * 1024 - 1]);
全是a？可以写成，没分配的部分从源卷读到的是a，已分配的部分从当前的卷读到是b。方便验证。

2020-12-14 07:46 UTC, bai-charisu commented on test/client/iotracker_splitor_unittest.cpp
> +    ASSERT_EQ('a', data[4 * 1024]);
同上。

2020-12-14 07:46 UTC, bai-charisu commented on test/client/iotracker_splitor_unittest.cpp
> +    ASSERT_EQ('a', data[4 * 1024 - 1]);
这个应该包含了上面那个全0的情况吧？是不是有点重复？

2020-12-14 07:51 UTC, ilixiaocui commented on src/client/io_tracker.cpp
> +                continue;
这里不需要continue吧

2020-12-14 07:51 UTC, ilixiaocui commented on src/client/io_tracker.cpp
> +    if (ret < 0) {
上面else不是已经处理了ret<0的场景？

 else {
        LOG(ERROR) << "splitor read io failed, "	        LOG(ERROR) << "splitor read io failed, "
                   << "offset = " << offset_ << ", length = " << length_;	                   << "offset = " << offset_ << ", length = " << length_;
    }

2020-12-14 07:51 UTC, ilixiaocui commented on src/client/io_tracker.cpp
> +        for (auto r : reqlist_) {
可以把这一段for封装一下

2020-12-14 07:51 UTC, ilixiaocui commented on src/client/io_tracker.cpp
> +        curveCombineCtx->curveCtx.offset = reqCtx->sourceInfo_.cloneFileOffset
为啥不直接是reqCtx->offset_

2020-12-14 07:51 UTC, ilixiaocui commented on src/client/io_tracker.cpp
> +        ret += ReadFromOrigin(originReadVec, fileInfo->userinfo);
这里ret为什么要加？ret返回的是0或者-1

2020-12-14 07:51 UTC, ilixiaocui commented on src/client/io_tracker.cpp
> +                            FileClient4ReadClone::GetFileClient4ReadClone();
为什么需要新增一个FileClient4ReadClone的类，直接使用原来的不行吗？无论是clone还是非clone, 读的流程不都是一样的？

2020-12-14 07:51 UTC, ilixiaocui commented on src/client/libcurve_file.h
> +class FileClient4ReadClone {
FileClient不能满足下面的接口要求吗

2020-12-14 07:51 UTC, ilixiaocui commented on src/client/request_scheduler.cpp
> +            if (!it->idinfo_.chunkExist) {
fake的request不是不会丢在这里面吗 为啥需要判断？

2020-12-14 07:51 UTC, ilixiaocui commented on src/client/splitor.cpp
> +                         mdsclient, metaCache, fileinfo, chunkidx)) {
chunkidx是用于？

2020-12-14 07:51 UTC, ilixiaocui commented on test/client/iotracker_splitor_unittest.cpp
> +       //     mc->UpdateChunkInfoByIndex(index, iter);
为啥这里全部注释掉了

2020-12-14 07:57 UTC, SeanHai commented on src/client/io_tracker.cpp
> +                r->subIoIndex_ = subIoIndex++;
> 这个是不是跟下面的r->subIoIndex_ = subIoIndex++重复了？

不会，这个下句就continue了

2020-12-14 08:01 UTC, SeanHai commented on src/client/io_tracker.cpp
> +        ret += ReadFromOrigin(originReadVec, fileInfo->userinfo);
> 为啥是+=？

意思是这两个都返回0（成功）才会成功，否则其中一个为失败（-1）都算失败。
这两可以表达成+ 或者 ||

2020-12-14 09:34 UTC, SeanHai commented on src/client/io_tracker.cpp
> +                    originReadVec.push_back(r);
> 改用emplace_back吧

done

2020-12-14 09:35 UTC, SeanHai commented on src/client/io_tracker.cpp
> +                    r->readData_ = zeroDataBuf;
> 这一段，直接r->readData_.resize就可以了吧

done

2020-12-14 09:36 UTC, SeanHai commented on src/client/io_tracker.cpp
> +    done->SetFailed(LIBCURVE_ERROR::OK);
> 上面SetFailed成FAILED之后，这里又Set成OK？？

done

2020-12-14 09:43 UTC, SeanHai commented on test/client/fake/mock_schedule.cpp
> +    // LOG(ERROR) << size;
> 为啥注释掉？

新增的单元测试用例复用了mock_schedule, 这段代码中关于size的逻辑感觉有点冗余，如果保留，size的获取需要对reqlist进行遍历，增加复杂度

2020-12-14 09:43 UTC, SeanHai commented on test/client/fake/mock_schedule.cpp
> +       // if (processed >= size) {
> 为啥注释掉？

同上

2020-12-14 10:56 UTC, SeanHai commented on test/client/iotracker_splitor_unittest.cpp
> +       // for (auto iter : sinfo.chunkvec) {
> 为啥注释掉？

这块注释掉的内容为调用GetOrAllocateSegment，获取一个segment，并且将相关信息（chunkIdInfo、copysetInfo）。注释掉的原因是：
1、这和上面 2. 设置GetOrAllocateSegmentresponse 功能类似，注释掉会在调用GetOrAllocateSegment时返回segment信息并更新metacache。
2、如果这更新了metacache，新增测试用例读普通卷（未写）和克隆卷（未写）时，需要调整offset到第二个segment，就与上面测试用例在形式上没法保持一致。如果保持原来不注释，可以先修改下offset测试看看

2020-12-14 11:10 UTC, SeanHai commented on test/client/iotracker_splitor_unittest.cpp
> +    ASSERT_EQ('a', data[4 * 1024 - 1]);
> 这个应该包含了上面那个全0的情况吧？是不是有点重复？

上面那个用例是读的普通卷，且读的chunk全都没写过，这个是读的普通卷，部分写过，部分没写过。严格来说也可以合成下面这个

2020-12-14 11:11 UTC, SeanHai commented on test/client/iotracker_splitor_unittest.cpp
> +    ASSERT_EQ(0, data[4 * 1024 - 1]);
> 这几个断言是为了断言data是全0的吗？可以写在循环里

是的，验证全0；这里形式主要是为了和上面之前的用例在形式上保持一致。

2020-12-14 11:15 UTC, SeanHai commented on test/client/iotracker_splitor_unittest.cpp
> +    ASSERT_EQ('a', data[4 * 1024 - 1]);
> 全是a？可以写成，没分配的部分从源卷读到的是a，已分配的部分从当前的卷读到是b。方便验证。

这里读当前卷和源卷复用是同一个mock_schedule，这个mock_schedule中是根据请求fakedata[index%10]来填充请求数据的（fakadata{'a','b',...'j'}）,可以调整下用例中已写过的chunk index，来使结果看起来更明显。

2020-12-14 11:19 UTC, SeanHai commented on src/client/io_tracker.h
> +                       UserInfo_t userInfo);
> userInfo改成const引用

done

2020-12-14 11:33 UTC, SeanHai commented on src/client/splitor.cpp
> +    ChunkIDInfo chunkIdInfo(0, 0, 0);
> 这个应该只有252行的else if里面用到吧，放到else if里面

done

2020-12-14 11:35 UTC, SeanHai commented on test/client/fake/fakeMDS.h
> +        if (!strcmp(request->filename().c_str(), "/clonesource")) {
> `request->filename() != "/clonesource"`

done

2020-12-14 11:36 UTC, SeanHai commented on test/client/iotracker_splitor_unittest.cpp
> +       // curve::client::MetaCache* mc = fileinstance_->GetIOManager4File()->
> 这里为什么注释掉了

这块注释掉的内容为调用GetOrAllocateSegment，获取一个segment，并且将相关信息（chunkIdInfo、copysetInfo）。注释掉的原因是：
1、这和上面 2. 设置GetOrAllocateSegmentresponse 功能类似，注释掉会在调用GetOrAllocateSegment时返回segment信息并更新metacache。
2、如果这更新了metacache，新增测试用例读普通卷（未写）和克隆卷（未写）时，需要调整offset到第二个segment，就与上面测试用例在形式上没法保持一致。如果保持原来不注释，可以先修改下offset测试看看

2020-12-14 11:58 UTC, SeanHai commented on test/client/iotracker_splitor_unittest.cpp
> +    MockRequestScheduler* mockschuler = new MockRequestScheduler;
> 这里最后没delete

上面之前的用例好像也漏掉了很多delete，我都加下

2020-12-14 11:58 UTC, SeanHai commented on test/client/iotracker_splitor_unittest.cpp
> +    MockRequestScheduler* mockschuler = new MockRequestScheduler;
> delete

done

2020-12-14 11:58 UTC, SeanHai commented on test/client/iotracker_splitor_unittest.cpp
> +    MockRequestScheduler* mockschuler = new MockRequestScheduler;
> delete

done

2020-12-14 11:58 UTC, SeanHai commented on test/client/iotracker_splitor_unittest.cpp
> +    MockRequestScheduler* mockschuler = new MockRequestScheduler;
> delete

done

2020-12-14 11:59 UTC, SeanHai commented on src/client/io_tracker.cpp
> +        ret += ReadFromOrigin(originReadVec, fileInfo->userinfo);
> 这里为什么用`+=`？

意思是这两个都返回0（成功）才会成功，否则其中一个为失败（-1）都算失败。
这两可以表达成+ 或者 ||

2020-12-14 12:08 UTC, SeanHai commented on src/client/io_tracker.cpp
> +                continue;
> 这里不需要continue吧

done

2020-12-14 12:11 UTC, SeanHai commented on src/client/io_tracker.cpp
> +    if (ret < 0) {
> 上面else不是已经处理了ret<0的场景？
> 
> else {
> LOG(ERROR) << "splitor read io failed, " LOG(ERROR) << "splitor read io failed, "
> << "offset = " << offset_ << ", length = " << length_; << "offset = " << offset_ << ", length = " << length_;
> }

ret = scheduler_->ScheduleRequest(reqlist_);
ret += ReadFromOrigin(originReadVec, &fileInfo->userinfo);
这里都会gengxret的值，意思是两个都成功（0）才算成功

2020-12-14 12:19 UTC, SeanHai commented on src/client/io_tracker.cpp
> +        curveCombineCtx->curveCtx.offset = reqCtx->sourceInfo_.cloneFileOffset
> 为啥不直接是reqCtx->offset_

reqCtx->offset_只是chunk内偏移，reqCtx->sourceInfo_.cloneFileOffset 在CalcRequestSourceInfo中会被计算出chunk偏移

2020-12-14 12:20 UTC, SeanHai commented on src/client/io_tracker.cpp
> +        ret += ReadFromOrigin(originReadVec, fileInfo->userinfo);
> 这里ret为什么要加？ret返回的是0或者-1

想表达两个都成功才算成功，用+ 或 || 应该都行，下面进行 ret<0 判断

2020-12-14 12:23 UTC, SeanHai commented on src/client/io_tracker.cpp
> +                            FileClient4ReadClone::GetFileClient4ReadClone();
> 为什么需要新增一个FileClient4ReadClone的类，直接使用原来的不行吗？无论是clone还是非clone, 读的流程不都是一样的？

一方面在IO_tracker中FileClient无法获取，另外如果复用原FileClient在打开源卷read时 FileClient::Read中
    ReadLockGuard lk(rwlock_)这个锁无法获得

2020-12-14 12:23 UTC, SeanHai commented on src/client/libcurve_file.h
> +class FileClient4ReadClone {
> FileClient不能满足下面的接口要求吗

理由同上

2020-12-14 12:44 UTC, SeanHai commented on src/client/request_scheduler.cpp
> +            if (!it->idinfo_.chunkExist) {
> fake的request不是不会丢在这里面吗 为啥需要判断？

丢到这里的请求包括非源卷的所有请求，最初不包括fake request，改动原因是：
如果只有真实的请求，fake请求之间在IOTracker中变量时填充fakedata, 那么reqcount_.store计数就只有真实请求，
RequestScheduler::ScheduleRequest 会对reqlist逐个处理，在场景假设有64个子请求，第一个是读写过的真实请求，后面都是fake请求，当第一个真实请求返回后在IOTracker::Done中会DestoryRequestList(); 这边遍历就会访问已经释放的空间。

2020-12-14 12:46 UTC, SeanHai commented on src/client/splitor.cpp
> +                         mdsclient, metaCache, fileinfo, chunkidx)) {
> chunkidx是用于？

Splitor::GetOrAllocateSegment 中更新ChunkIDInfo使用
ChunkIDInfo chunkIdInfo(0, 0, 0);
chunkIdInfo.chunkExist = false;
metaCache->UpdateChunkInfoByIndex(chunkidx, chunkIdInfo);

2020-12-14 12:47 UTC, SeanHai commented on test/client/iotracker_splitor_unittest.cpp
> +       //     mc->UpdateChunkInfoByIndex(index, iter);
> 为啥这里全部注释掉了

这块注释掉的内容为调用GetOrAllocateSegment，获取一个segment，并且将相关信息（chunkIdInfo、copysetInfo）。注释掉的原因是：
1、这和上面 2. 设置GetOrAllocateSegmentresponse 功能类似，注释掉会在调用GetOrAllocateSegment时返回segment信息并更新metacache。
2、如果这更新了metacache，新增测试用例读普通卷（未写）和克隆卷（未写）时，需要调整offset到第二个segment，就与上面测试用例在形式上没法保持一致。如果保持原来不注释，可以先修改下offset测试看看

2020-12-16 09:47 UTC, SeanHai commented on test/client/iotracker_splitor_unittest.cpp
> +    MockRequestScheduler* mockschuler = new MockRequestScheduler;
> 这里最后没delete

在TearDown 的fileinstance_->UnInitialize() ->   iomanager4file_.UnInitialize();会delete

2020-12-17 11:52 UTC, SeanHai commented on src/client/libcurve_file.h
> +    FileClient *fileClient_ = nullptr;
> 用unique_ptr吧

done

2020-12-19 08:21 UTC, SeanHai commented on test/client/iotracker_splitor_unittest.cpp
> +    LOG(ERROR) << "address = " << &data;
> 这个用不到吧？

done

2020-12-19 08:22 UTC, SeanHai commented on src/client/io_tracker.cpp
> +    FileClient4ReadClone &fileClient4Clone =
> 可以把逻辑都封装到`FileClient4ReadClone`里面，提供一个接口，这里直接调用就行了。

done

2020-12-23 09:03 UTC, ilixiaocui commented on src/client/libcurve_client.cpp
> +                curve::common::SplitString(iter->second, FD_TIME_DELIM,
这里直接封装一个函数出去吧
Getfd()

2020-12-23 09:03 UTC, ilixiaocui commented on src/client/libcurve_client.cpp
> +                if (fdtimestamp.size() != 2) {
这里是第三次重复了

2020-12-23 09:03 UTC, ilixiaocui commented on src/client/libcurve_client.cpp
> +                if (time(0) - timestamp > FD_TIMEOUT) {
这样减出来不是负的吗

2020-12-23 09:08 UTC, SeanHai commented on src/client/libcurve_client.cpp
> +                if (time(0) - timestamp > FD_TIMEOUT) {
> 这样减出来不是负的吗

不会，time(0)是现在的时间，timestamp是之前访问时保存的，所以肯定大于timestamp

2020-12-23 09:10 UTC, SeanHai commented on include/client/libcurve.h
> +    int Closefd();
> 既然是后台线程来删除，作为private感觉更合理

done

2020-12-23 09:10 UTC, SeanHai commented on include/client/libcurve.h
> +    std::thread closeThread;
> fdCloseThread

done

2020-12-23 09:13 UTC, SeanHai commented on include/client/libcurve.h
> +    std::thread closeThread;
> fdCloseThread
done, fdCloseThread_

2020-12-23 09:17 UTC, SeanHai commented on include/client/libcurve.h
> +class OriginReader {
> SourceReader?

done

2020-12-23 09:20 UTC, SeanHai commented on src/client/libcurve_client.cpp
> +}
> 这里打一下reader stop的日志

done

2020-12-23 09:28 UTC, SeanHai commented on src/client/libcurve_client.cpp
> +    }
> 这里打一下reader run success 类似的日志

done

2020-12-23 09:29 UTC, SeanHai commented on src/client/libcurve_client.cpp
> +        curveCombineCtx->curveCtx.offset = reqCtx->sourceInfo_.cloneFileOffset
> 这里为什么需要offset相加

reqCtx->offset_只是chunk内偏移，reqCtx->sourceInfo_.cloneFileOffset 在CalcRequestSourceInfo中会被计算出chunk偏移

2020-12-23 09:29 UTC, SeanHai commented on include/client/libcurve.h
> +    std::unordered_map<std::string, std::string> fdMap_;
> 这里注释一下first是什么 second是什么

done

2020-12-23 09:33 UTC, SeanHai commented on src/client/libcurve_client.cpp
> +                if (fdtimestamp.size() != 2) {
> 这里是第三次重复了

done

2020-12-23 10:54 UTC, wu-hanqing commented on include/client/libcurve.h
> +    std::mutex  mtx_;
这个锁改成读写锁吧

2020-12-23 11:11 UTC, SeanHai commented on include/client/libcurve.h
> +    std::mutex  mtx_;
> 这个锁改成读写锁吧

done

2020-12-23 11:20 UTC, SeanHai commented on include/client/libcurve.h
> +    std::unordered_map<std::string, std::string> fdMap_;
> 这里改成`std::unordered_map<std::string, std::pair<int, uint64_t> fdMap_`
> `std::pair<int, uint64_t>` 第一个存fd，第二个存timestamp
> 或者也可以把<fd,timestamp>再封装一次，用string存，太蛮烦了。

done

2020-12-23 12:17 UTC, SeanHai commented on src/client/splitor.cpp
>      if (errCode == MetaCacheErrorType::CHUNKINFO_NOT_FOUND) {
> 这里应该少了一个条件，如果读请求的时候，把chunk标记为chunkExist=false，后续的写请求会拿到一个chunk不存在的ChunkInfo。这种情况下，也需要取分配segment

done

2020-12-23 12:45 UTC, SeanHai commented on src/client/libcurve_client.cpp
> +OriginReader::OriginReader() : fileClient_(new FileClient()) {}
> 这个类的实现，放到一个单独的cpp文件中吧。

done

2020-12-24 04:48 UTC, SeanHai commented on include/client/libcurve.h
> +#define FD_TIMEOUT             300
> 这里的参数，用配置文件设置吧。

done

2020-12-24 04:51 UTC, SeanHai commented on include/client/libcurve.h
> +class OriginReader {
done
在curveclient初始化时进行 sourcereader的初始化，如果放到IOTracker::ReadFromSource每次都会去尝试初始化，并且感觉sourcereader和curveclient的级别好像差不多

2020-12-24 06:54 UTC, wu-hanqing commented on src/client/libcurve_client.cpp
> +}  // namespace curve
文件末尾应该要有一个空行，没有cpplint会报错

2020-12-24 06:54 UTC, wu-hanqing commented on src/client/libcurve_file.h
> +    /**
这里几个函数的缩进

2020-12-24 06:54 UTC, wu-hanqing commented on src/client/source_reader.cpp
> +            curve::common::WriteLockGuard writeLockGuard(rwLock_);
这个锁的流程，应该是先拿读锁，如fdMap_里面查找，如果找到了，就可以直接用。
如果没找到，拿写锁去新建一个。

2020-12-24 06:54 UTC, wu-hanqing commented on src/client/source_reader.cpp
> +            fdMap_[fileName] = std::make_pair(fd, time(0));
这里为什么都要更新成time(0)？
我的理解是，如果新建，或者使用的时候，更新timestap为当前的时间，比如用`GetTimeofDayMs`来记录。
后台线程在扫描关闭的时候，对比当前的时间戳与fd的时间戳，如果超过阈值，就关闭。

2020-12-24 06:54 UTC, wu-hanqing commented on src/client/splitor.cpp
> +        if (!chunkIdInfo.chunkExist && iotracker->Optype() == OpType::WRITE) {
这里的判断，最好放到183行吧

2020-12-24 06:59 UTC, SeanHai commented on src/client/libcurve_client.cpp
> +}  // namespace curve
done

2020-12-24 06:59 UTC, SeanHai commented on src/client/libcurve_file.h
> +    /**
> 这里几个函数的缩进

done

2020-12-24 07:05 UTC, SeanHai commented on src/client/source_reader.cpp
> +            fdMap_[fileName] = std::make_pair(fd, time(0));
> 这里为什么都要更新成time(0)？
> 我的理解是，如果新建，或者使用的时候，更新timestap为当前的时间，比如用`GetTimeofDayMs`来记录。
> 后台线程在扫描关闭的时候，对比当前的时间戳与fd的时间戳，如果超过阈值，就关闭。

time(0)就是获取现在时间戳

2020-12-24 07:08 UTC, SeanHai commented on src/client/source_reader.cpp
> +            curve::common::WriteLockGuard writeLockGuard(rwLock_);
done

2020-12-24 07:24 UTC, SeanHai commented on src/client/splitor.cpp
> +        if (!chunkIdInfo.chunkExist && iotracker->Optype() == OpType::WRITE) {
> 这里的判断，最好放到183行吧

done

2020-12-24 10:56 UTC, wu-hanqing approved these changes

2020-12-24 12:02 UTC, SeanHai commented on src/client/io_tracker.cpp
> +    return sourceReader.Read(reqCtxVec, userInfo);
> SourceReader::GetInstance().Read(reqCtxVec, userInfo)?

done

2020-12-24 12:03 UTC, SeanHai commented on src/client/io_tracker.h
> +     *  read from the origin
> read from source

done

2020-12-24 12:12 UTC, ilixiaocui commented on test/client/fake/mock_schedule.cpp
> +       // }
不要的代码直接删掉吧

2020-12-25 01:47 UTC, SeanHai commented on src/client/libcurve_client.cpp
> +    } else {
> error日志

done

2020-12-25 01:49 UTC, SeanHai commented on src/client/source_reader.cpp
> +    }
> else 也打下日志吧 not running or already stopped

done

2020-12-25 01:54 UTC, SeanHai commented on src/client/source_reader.cpp
> +            fileClient_->Close(pair.second.first);
> close有返回值吗？

有的，修改后增加了判断
            if (LIBCURVE_ERROR::OK != fileClient_->Close(pair.second.first)) {
                LOG(ERROR) << "Close fd failed, fd = " << pair.second.first;
                return;
            }

2020-12-25 01:55 UTC, SeanHai commented on src/client/source_reader.cpp
> +            iter->second.second = time(0);
> 为什么这里赋值为time(0)

time(0)就是当前时间戳

2020-12-25 01:56 UTC, SeanHai commented on src/client/source_reader.cpp
> +        curve::common::WriteLockGuard lk(rwLock_);
> 跟curve::common::ReadLockGuard readLockGuard(rwLock_); 命名一致吧？

done

2020-12-25 01:59 UTC, SeanHai commented on src/client/source_reader.cpp
> +        auto iter = fdMap_.find(fileName);
> 为啥这里还需要再find一次，而不是直接open

因为上面拿的是读锁，有可能多个线程同时获取到然后去fdMap中查询结果都为不存在，下面获取写锁时，其中一个首先获得，其他等待，如果不再查询一次就会出现打开多次的问题

2020-12-25 02:01 UTC, SeanHai commented on test/client/fake/mock_schedule.cpp
> +       // }
> 不要的代码直接删掉吧

done

2020-12-25 02:17 UTC, SeanHai commented on src/client/source_reader.cpp
> +        curve::common::WriteLockGuard lk(rwLock_);
> 跟curve::common::ReadLockGuard readLockGuard(rwLock_); 命名一致吧？

done

2020-12-25 08:17 UTC, ilixiaocui approved these changes

2020-12-25 08:18 UTC, merged