Fix clone delete
opencurve/curve pull request #176
Opened 2020-11-30 12:18 UTC by cw123

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

2020-12-08 09:30 UTC, xu-chaojie requested changes

2020-12-08 09:30 UTC, xu-chaojie commented on src/snapshotcloneserver/clone/clone_service_manager.cpp
> +                    ret = cloneCore_->HandleDeleteCloneInfo(cloneInfo);
如果在这之间来一个flatten，会导致status变error，考虑下这种情况

2020-12-08 09:30 UTC, xu-chaojie commented on src/snapshotcloneserver/clone/clone_service_manager.cpp
> +                case CloneStatus::error:
error的时候，dest也有可能不存在了，这样的情况下会怎么样?

2020-12-10 09:07 UTC, ilixiaocui commented on src/snapshotcloneserver/clone/clone_service_manager.cpp
> +        *refStatus = CloneRefStatus::kNoRef;
这个是表示没有克隆任务？kNoRef最开始看的时候以为是src没有相关的克隆任务，kNoCloneTask? 或者直接返回kErrCodeSuccess;

2020-12-10 09:17 UTC, ilixiaocui commented on src/snapshotcloneserver/snapshotclone_service.h
> +    void HandleGetCloneRefStatusAction(brpc::Controller* bcntl,
没有注册的流程吗？

2020-12-11 02:45 UTC, cw123 commented on src/mds/snapshotcloneclient/snapshotclone_client.cpp
> +    if (tempStatus == CloneRefStatus::kNoRef
在明确有引用的情况下，不需要再查询dest在不在。
查询是否有引用，有3个状态，有引用，无引用，可能有引用。如果明确是否有引用，就不需要进一步确认。
如果是可能有引用，就把可能有引用的文件列表返回mds，mds查询下这些文件在不在，如果不在了，就说明没有引用了。

2020-12-11 02:45 UTC, cw123 commented on src/mds/nameserver2/curvefs.cpp
> +#include <chrono>    //NOLINT
我本地的cpplint过不去

2020-12-11 02:46 UTC, cw123 commented on conf/mds.conf
> +mds.snapshotcloneclient.addr=127.0.0.1:5555
没有用注册机制，mds加载的时候，自动加载快照克隆服务。

2020-12-11 02:48 UTC, cw123 commented on src/snapshotcloneserver/clone/clone_service_manager.cpp
> +        *refStatus = CloneRefStatus::kNoRef;
GetCloneInfoList返回-1，说明没有查到相关的记录。
kNoRef有两种情况，一种是没有查到对应的记录；一个是虽然有克隆记录，但是是非lazy处理完了，或者flatten处理完了，已经没有依赖了。

2020-12-11 02:48 UTC, cw123 commented on src/snapshotcloneserver/snapshotclone_service.h
> +    void HandleGetCloneRefStatusAction(brpc::Controller* bcntl,
没有用注册机制，mds加载的时候，自动加载快照克隆服务。

2020-12-11 03:25 UTC, cw123 commented on src/mds/snapshotcloneclient/snapshotclone_client.h
> +     *         modify the correctedSn of the chunk
这里是从别的地方拷过来的，漏了改。
已经修改了

2020-12-14 03:07 UTC, ilixiaocui commented on src/mds/nameserver2/curvefs.cpp
> +#include <chrono>    //NOLINT
ci上的是可以的

2020-12-14 06:21 UTC, ilixiaocui commented on src/mds/nameserver2/curvefs.cpp
> +        for (int i = 0; i < recordNum; i++) {
直接 i < fileCheckList.size(); ?

2020-12-14 06:21 UTC, ilixiaocui commented on src/mds/nameserver2/curvefs.cpp
> +                    continue;
这里continue可以去掉

2020-12-14 06:21 UTC, ilixiaocui commented on src/mds/nameserver2/curvefs.cpp
> +                    continue;
if (ret2 == StatusCode::kFileNotExists) {
} else if (ret2 == StatusCode::kOK) {
  // 判断inode
} else {
   print error log
}

2020-12-14 06:21 UTC, ilixiaocui commented on src/mds/nameserver2/curvefs.cpp
> +    bool hasCloneRef = false;
*isHasCloneRely = false, 不需要新增变量hasCloneRef？

2020-12-14 06:21 UTC, ilixiaocui commented on src/mds/nameserver2/curvefs.h
> +                                             bool *isHasCloneRely);
参数对齐

2020-12-14 06:21 UTC, ilixiaocui commented on src/snapshotcloneserver/common/snapshotclone_meta_store_etcd.cpp
> +    // if old record not exist, return failed
为啥要加这个逻辑

2020-12-14 06:25 UTC, ilixiaocui commented on conf/snapshot_clone_server.conf
> +# CloneServiceManager引用计数后台扫描每条记录间隔
1. 一个pr里面就一个提交吧 这样比较好看一些
2. 不要通过close/reopen的方式触发ci, 本地commit --ammend；然后push -f 重新提交下就可以触发了

2020-12-14 07:07 UTC, cw123 commented on src/snapshotcloneserver/clone/clone_service_manager.cpp
> +                case CloneStatus::error:
翻了代码，error的时候，引用计数已经减了。
逻辑改为，error的状态任务也是没有引用的。

2020-12-14 07:09 UTC, cw123 commented on src/mds/nameserver2/curvefs.cpp
> +        for (int i = 0; i < recordNum; i++) {
在循环之前，把结果取出来，避免循环中多次调用

2020-12-14 07:16 UTC, cw123 commented on src/mds/nameserver2/curvefs.cpp
> +    bool hasCloneRef = false;
引入新的变量，可以做到，传入的变量，只有在执行成功的时候，才会被赋值。

2020-12-14 07:16 UTC, cw123 commented on src/mds/nameserver2/curvefs.h
> +                                             bool *isHasCloneRely);
done

2020-12-14 07:16 UTC, cw123 commented on src/mds/nameserver2/curvefs.cpp
> +                    continue;
done

2020-12-14 07:22 UTC, cw123 commented on src/snapshotcloneserver/common/snapshotclone_meta_store_etcd.cpp
> +    // if old record not exist, return failed
这样修改，是希望update的时候，如果旧记录不存在，update就返回失败。
为什么增加这个改动，因为有一种场景，如果3、4并发出现，4先get clone info，然后3删除了cloneinfo，这时4又update clone info，按照改动之前的代码逻辑，会update 成功，删除的clone info 又会出现。
1、sorce lazy clone dest.
2、delete dest
3、backend delete sorce->dest clone info（这一步会删除clone info）
4、flatten sorce->dest (这一步会先 get clone info，再update clone info)

2020-12-14 07:23 UTC, cw123 commented on conf/snapshot_clone_server.conf
> +# CloneServiceManager引用计数后台扫描每条记录间隔
ok

2020-12-14 07:58 UTC, ilixiaocui commented on src/mds/nameserver2/curvefs.cpp
> +    bool hasCloneRef = false;
*isHasCloneRely = hasCloneRef;

这里没有执行成功一说吧，都是要赋值的，要不就是true，要不就是false?

2020-12-18 06:15 UTC, xu-chaojie approved these changes

2020-12-18 06:16 UTC, merged