CurverBs:Add size of chunkfilepool to optimize whether the logical po…
opencurve/curve pull request #1804
Opened 2022-08-10 12:26 UTC by yuxubinchen

…ol is allocated

Signed-off-by: Zhao ZeYu <2302370185@qq.com>

### What problem does this PR solve?

Issue Number: #1058 

Problem Summary:

### What is changed and how it works?

What's Changed:add chunkfilepool size at topology_stat to optimize whether the logical pool is allocated

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

2022-08-10 12:49 UTC, yuxubinchen commented
recheck

2022-08-23 03:13 UTC, xu-chaojie commented on curvefs/test/mds/mock/mock_topology.h
> +                uint32_t port, Server *out));
Do not introduce changes unrelated to the issue

2022-08-23 03:17 UTC, xu-chaojie commented on src/mds/topology/topology.cpp
> +    for (auto po : serverMap_) {
Do not introduce changes unrelated to the issue

2022-08-23 03:18 UTC, cw123 commented on src/mds/topology/topology.cpp
> +    for (auto po : serverMap_) {
change po to a meaningful name

2022-08-23 03:18 UTC, xu-chaojie commented on src/mds/topology/topology.cpp
> +    LOG(INFO) << "AddServer: " << data.GetId();
make this log more clear

2022-08-23 03:20 UTC, cw123 commented
Combine 3 commits into one commit

2022-08-23 03:21 UTC, xu-chaojie commented on src/mds/topology/topology_chunk_allocator.cpp
> -        diskCapacity = diskCapacity * poolUsagePercentLimit_ / 100;
poolUsagePercentLimit_ is required, indicating the percentage of chunkfilepool usage

2022-08-23 03:44 UTC, cw123 commented on src/chunkserver/register.h
> +    uint64_t chunkfilepoolsize;
use Camel-Case

2022-08-23 03:44 UTC, cw123 commented on proto/heartbeat.proto
> +    required uint64 chunkfilepoolSize = 8;
use Camel-Case

2022-08-23 03:44 UTC, cw123 commented on src/mds/topology/topology_stat.h
> +    uint64_t chunkfilepoolSize;
use Camel-Case

2022-08-23 03:44 UTC, cw123 commented on src/mds/topology/topology_stat.h
> +    uint64_t *chunkpoolsize) = 0;
Camel-Case

2022-08-23 05:52 UTC, cw123 commented on src/mds/topology/topology_stat.cpp
> +    }
delete spaces

2022-08-23 05:52 UTC, cw123 commented on src/mds/topology/topology_stat.cpp
> +    int ret = topo_-> GetBelongPhysicalPoolId(csId, &belongPhysicalPoolId);
Judgment return value

2022-08-24 11:50 UTC, yuxubinchen commented
recheck

2022-08-24 15:00 UTC, yuxubinchen commented
recheck

2022-08-26 04:50 UTC, yuxubinchen commented
这个日志很奇怪，看起来测试点是过了但是，会一直循环跑下去，直到超时1h

2022-08-29 07:21 UTC, yuxubinchen commented
@cw123

2022-08-31 03:48 UTC, yuxubinchen commented
recheck

2022-09-08 09:08 UTC, yuxubinchen commented
recheck

2022-09-09 03:25 UTC, yuxubinchen commented
recheck

2022-09-09 03:38 UTC, yuxubinchen commented
recheck

2022-09-11 02:05 UTC, yuxubinchen commented
recheck

2022-09-11 02:54 UTC, yuxubinchen commented
recheck

2022-09-13 06:49 UTC, yuxubinchen commented
recheck

2022-09-16 13:17 UTC, yuxubinchen commented
recheck

2022-09-16 13:22 UTC, yuxubinchen commented
recheck

2022-09-17 03:12 UTC, yuxubinchen commented
recheck

2022-09-17 07:05 UTC, yuxubinchen commented
recheck

2022-09-18 03:16 UTC, yuxubinchen commented
根据chunkserve conf的配置，如果使用chunkfielpool，mds使用chunkfilepool的size,否则使用原来的物理容量.

2022-09-18 04:35 UTC, yuxubinchen commented
recheck

2022-09-18 04:35 UTC, yuxubinchen commented
recheck

2022-09-18 06:44 UTC, yuxubinchen commented
recheck

2022-09-18 06:47 UTC, yuxubinchen commented
recheck

2022-09-18 06:51 UTC, yuxubinchen commented
recheck

2022-09-18 09:19 UTC, yuxubinchen commented
recheck

2022-09-26 07:14 UTC, xu-chaojie commented on src/mds/topology/topology_chunk_allocator.cpp
> +            continue;
这个地方的逻辑是不对的，总的空间是chunkfilepool的空间，使用掉的空间是alloc的空间，剩余空间应该是两者相减，再通过poolUsagePercentLimit_这个字段来预留一部分可分配空间防止failover时，空间溢出

2022-09-26 07:41 UTC, xu-chaojie commented on src/mds/topology/topology_chunk_allocator.cpp
> +            continue;
整个思路再给你理一下，分为几种情况：
1. 不使用chunkfilepool的时候：
此时，总量应该是磁盘的全部空间，分配量是alloc的空间，可用空间是两者相减，但是需要预留两种空间，一是raft WAL的空间，而是failover的空间
2. 使用chunkfilepool，不使用walpool的情况：
这时，总量是chunkfilepool的总空间，分配量是alloc的空间，可用空间是两者相减，但是需要预留failover的空间
3. 使用chunkfilepool，并且使用walpool的情况：
与第2种情况一样：
4.  使用chunkfilepool，walpool共用chunkfilepool的情况：
这时，总量是chunkfilepool的总空间，分配量是alloc的空间，可用空间时两者相减，但是需要预留两个空间，一是raft WAL的空间，而是failover的空间

2022-09-26 08:12 UTC, yuxubinchen commented on src/mds/topology/topology_chunk_allocator.cpp
> +            continue;
Ok thanks, I will fix it, I originally thought that the size of the chunkfilepool is the size of the available space. So no subtracting alloc. I get it now

2022-09-28 07:39 UTC, yubindy commented on src/mds/topology/topology_chunk_allocator.cpp
> +            continue;
Do you need any strategy for reservation? The feasible method for me now is to use the size of chunkfilePool minus the size of walPool and the size of copyset that have been used now. I think it should be extra reservation, which may be reserved according to the percentage of the remaining size. Stay, no, I don't have any better ideas.
对于预留需要什么策略吗，我现在可行的方法是使用chunkfilePool的size减去现在已经使用walPool的size和copyset的size,我觉得是应该是需要进行额外预留，可能可以按照剩下size的百分比预留，否侧我没有什么比较好的想法了

2022-09-28 11:26 UTC, yubindy commented on src/mds/topology/topology_chunk_allocator.cpp
> +            continue;
而对于walPool的size和copyset的size,因为共用一个chunkfilepool 的接口，我能想到统计size的是用walpool的目录下的文件个数*segment_size

2022-09-29 13:00 UTC, yubindy commented
recheck

2022-09-30 10:25 UTC, yubindy commented
recheck

2022-10-11 12:40 UTC, yubindy commented
recheck

2022-10-12 02:47 UTC, yubindy commented
recheck

2022-10-12 05:59 UTC, yubindy commented
recheck

2022-10-14 01:35 UTC, yubindy commented
recheck

2022-10-14 08:37 UTC, yubindy commented
recheck

2022-10-15 08:49 UTC, yubindy commented
recheck

2022-10-16 05:18 UTC, yubindy commented
recheck

2022-10-16 07:56 UTC, yubindy commented
recheck

2022-10-16 11:28 UTC, yubindy commented
![image](https://user-images.githubusercontent.com/74901886/196032774-a6d5a153-c0d5-4374-93f0-cd75b0f4bcec.png)

2022-10-16 11:32 UTC, yubindy commented
![image](https://user-images.githubusercontent.com/74901886/196032824-d0075299-9d88-4e11-a172-dd09d5b15464.png)
在快照这里一直显示是创建的文件比剩余的chunkfilepool的size大,所以一直失败，而我在增加日志确定后确实是比chunkfilepool的size大，所以会一直失败

2022-10-16 11:34 UTC, yubindy commented
![image](https://user-images.githubusercontent.com/74901886/196033055-8e4ef89b-bd06-4ecb-8572-d4eb09f4896b.png)

2022-10-16 11:44 UTC, yubindy commented
![image](https://user-images.githubusercontent.com/74901886/196033539-7c9ebda0-067e-4852-a81c-e43d8d404a9a.png)

2022-10-18 02:05 UTC, yubindy commented
recheck

2022-10-18 02:23 UTC, yubindy commented
recheck

2022-10-18 05:57 UTC, yubindy commented
recheck

2022-10-18 11:26 UTC, yubindy commented
recheck

2022-10-19 03:48 UTC, yubindy commented
recheck

2022-10-19 08:25 UTC, yubindy commented
recheck

2022-10-19 12:31 UTC, yubindy commented
recheck

2022-10-20 08:30 UTC, xu-chaojie commented on conf/mds.conf
> +mds.topology.ChunkFilePoolfailoverReserve=24
一个zone 标准配置20台节点，允许3台节点failover，那么剩余17台机器需要承载原先20台机器的空间，那么20台机器每台最多占多少空间？

2022-10-20 08:39 UTC, xu-chaojie commented on src/chunkserver/chunkserver.cpp
> +    uint32_t useChunkFilePoolAsWalPoolReserve = 15;
Shouldn't this come from the config file?

2022-10-20 11:29 UTC, yubindy commented
recheck

2022-10-20 11:31 UTC, yubindy commented
recheck

2022-10-20 12:50 UTC, yubindy commented
![image](https://user-images.githubusercontent.com/74901886/196953448-06ea3336-c04b-4046-8a95-aa0f7f77aa65.png)

2022-10-24 08:00 UTC, xu-chaojie commented on conf/mds.conf
> +mds.topology.ChunkFilePoolfailoverReserve=15
remove “mds.topology.PoolUsagePercentLimit ” when it not needed

2022-10-24 08:04 UTC, xu-chaojie commented on src/mds/topology/topology_chunk_allocator.cpp
> +            diskCapacity = diskCapacity * available / 100;
available here has no assignment？

2022-10-24 08:06 UTC, xu-chaojie commented on src/mds/topology/topology_chunk_allocator.h
> +        if (useWalasChunkFilePool.load(std::memory_order_acquire)) {
use Wal as ChunkFilePool   ？

2022-10-26 06:45 UTC, xu-chaojie commented on proto/topology.proto
> +    required uint64 chunkFilepoolSize = 8;
use optional for backward compatibility

2022-10-26 06:49 UTC, xu-chaojie requested changes

2022-10-26 06:49 UTC, xu-chaojie commented on proto/heartbeat.proto
> +    required uint64 chunkFilepoolSize = 8;
use optional for backward compatibility

2022-10-26 06:49 UTC, xu-chaojie commented on src/mds/topology/topology_chunk_allocator.cpp
> +            available -= chunkFilePoolAllocHelp_->getAvailable();
why use -= ？

2022-10-27 09:46 UTC, cw123 commented on src/mds/topology/topology_chunk_allocator.h
> +class ChunkFilePoolAllochelp {
ChunkFilePoolAllochelp -> ChunkFilePoolAllocHelp

2022-10-27 09:46 UTC, cw123 commented on src/mds/topology/topology_chunk_allocator.h
> +    uint32_t available;
What is the unit, is it bytes or a percentage？
add the comment

2022-10-27 09:46 UTC, cw123 commented on src/mds/topology/topology_service_manager.cpp
> +        useChunkFilePoolAsWalPool = request->usechunkfilepoolaswalpool();
Check if this field is set before use

2022-10-27 09:46 UTC, cw123 commented on src/mds/topology/topology_service_manager.cpp
> +        useChunkFilePoolAsWalPoolReserve =
Check if this field is set before use

2022-10-27 14:33 UTC, yubindy commented
recheck

2022-10-28 02:29 UTC, xu-chaojie commented on src/chunkserver/register.cpp
> +    req.set_usechunkfilepoolaswalpoolreserve(
indentation

2022-10-28 02:50 UTC, cw123 commented on src/mds/topology/topology_service_manager.cpp
> +    if (request->has_chunkfilepoolsize()) {
考虑一下，这里的几个变量。如果注册的时候，request没有设置，是否要继续注册。
If the request is not set during registration, whether to continue the registration.

2022-10-28 02:50 UTC, cw123 commented on src/mds/topology/topology_chunk_allocator.h
> +    std::shared_ptr<ChunkFilePoolAllocHelp> ChunkFilePoolAllocHelp_;
类定义使用以大写字母开头；成员变量以小写字母开头，加上_后缀；函数以大写字母开头；函数的入参以小写字母开头，后面不加_后缀。新加的代码按照这种风格统一一下，就不一一指出了。
Class definitions start with an uppercase letter; member variables start with a lowercase letter and _ suffix; functions start with an uppercase letter; function input parameters start with a lowercase letter, without the _ suffix.

2022-10-28 02:50 UTC, cw123 commented on src/mds/topology/topology_chunk_allocator.cpp
> +            available *= ChunkFilePoolAllocHelp_->getAvailable();
如果GetRemainingSpaceInLogicalPool执行多次，这里的available是不是会越变越小，每走到一次这个分支，都会改变available的值。
这个逻辑增加一个单元测试，在使用chunk file pool的场景下，多次执行GetRemainingSpaceInLogicalPool，判断获取的remaining space是否正确。

If GetRemainingSpaceInLogicalPool is executed multiple times, will the available value here become smaller and smaller? Every time this branch is reached, the value of available will be changed.
This logic adds a unit test. In the scenario of using chunk file pool, execute GetRemainingSpaceInLogicalPool multiple times to determine whether the acquired remaining space is correct.

2022-10-31 02:42 UTC, xu-chaojie approved these changes

2022-10-31 02:55 UTC, cw123 approved these changes

2022-10-31 03:08 UTC, merged