curvebs/mds: add curvebs logicpool io metric
opencurve/curve pull request #2176
Opened 2022-12-29 06:26 UTC by wuhongsong

signed-off-by: hzwuhongsong [hzwuhongsong@corp.netease.com](mailto:hzwuhongsong@corp.netease.com)

2022-12-29 06:31 UTC, wuhongsong commented
![image](https://user-images.githubusercontent.com/13897133/209912957-cfa3901d-34f6-4a95-9774-b73cec2a3c00.png)

![image](https://user-images.githubusercontent.com/13897133/209912890-5732f1b4-995c-409b-9f13-f45e10bca7ce.png)

2022-12-29 06:32 UTC, wuhongsong commented
cicheck

2022-12-29 07:54 UTC, wuhongsong commented
cicheck

2022-12-29 08:30 UTC, wuhongsong commented
cicheck

2022-12-29 08:52 UTC, aspirer commented on src/mds/topology/topology_metric.cpp
> +            << writeIOPS << ", write bs: "
bps?

2022-12-29 08:52 UTC, aspirer commented on src/mds/topology/topology_metric.cpp
> +                  << iterCsStat.writeIOPS << ", write bs: "
bps?

2022-12-29 09:01 UTC, aspirer commented on src/mds/topology/topology_metric.cpp
> +                  << iterCsStat.writeIOPS << ", write bs: "
cluster readbps:

2022-12-29 09:47 UTC, aspirer requested changes

2022-12-29 09:47 UTC, aspirer commented on src/mds/topology/topology_metric.h
> +    bvar::Status<uint32_t> writeRate;
should use uint64_t

2023-01-03 02:27 UTC, wuhongsong commented on src/mds/topology/topology_metric.cpp
> +            << writeIOPS << ", write bs: "
fix

2023-01-03 02:27 UTC, wuhongsong commented on src/mds/topology/topology_metric.cpp
> +                  << iterCsStat.writeIOPS << ", write bs: "
fix

2023-01-03 02:27 UTC, wuhongsong commented on src/mds/topology/topology_metric.h
> +    bvar::Status<uint32_t> writeRate;
fix

2023-01-03 02:27 UTC, wuhongsong commented
cicheck

2023-01-03 05:38 UTC, SeanHai approved these changes

2023-01-03 05:51 UTC, aspirer approved these changes

2023-01-03 05:52 UTC, merged