etcd: etcd-backup.sh
opencurve/curve pull request #234
Opened 2021-01-26 08:43 UTC by ilixiaocui

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

2021-01-26 08:49 UTC, wu-hanqing requested changes

2021-01-26 08:49 UTC, wu-hanqing commented on etcd-backup.sh
> +    exit 0
出错退出可以exit 1吧？

2021-01-26 08:49 UTC, wu-hanqing commented on etcd-backup.sh
> +    exit 0
同上

2021-01-26 08:49 UTC, wu-hanqing commented on etcd-backup.sh
> +# 超过backupnum的备份数据删除
这里应该可以用 `find ${backupPath} -name "snapshot_*" -mtime +7 | xargs rm`

2021-01-26 08:55 UTC, SeanHai commented on etcd-backup.sh
> +leader_etcd=`curve_ops_tool etcd-status | grep "current etcd:" | awk -F" " '{print $3}'`
awk -F" " (默认分隔符，可以省略），加上也可以吧

2021-01-26 09:10 UTC, ilixiaocui commented on etcd-backup.sh
> +leader_etcd=`curve_ops_tool etcd-status | grep "current etcd:" | awk -F" " '{print $3}'`
done

2021-01-26 09:10 UTC, ilixiaocui commented on etcd-backup.sh
> +    exit 0
done

2021-01-26 09:10 UTC, ilixiaocui commented on etcd-backup.sh
> +# 超过backupnum的备份数据删除
👍

2021-01-27 02:54 UTC, aspirer commented on etcd-backup.sh
> +# 备份路径
如果要merge到主库，还是改成英文比较合适。

2021-01-27 03:02 UTC, aspirer commented
恢复也写个脚本？主要是那些参数看着还挺复杂的，临时准备不知道好不好找。

2021-02-24 02:18 UTC, opencurveadmin commented
recheck

2021-02-24 02:26 UTC, opencurveadmin commented
recheck

2021-05-25 03:03 UTC, closed without merging