[feature]add fmtlib(#2291)
opencurve/curve pull request #2367
Opened 2023-04-01 04:14 UTC by Tangruilin

### What problem does this PR solve?

Issue Number: #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

2023-04-05 12:32 UTC, Tangruilin commented
/recheck

2023-04-05 12:35 UTC, Tangruilin commented
recheck

2023-04-06 11:22 UTC, Tangruilin commented
are there someone review this PR

2023-04-07 01:15 UTC, fansehep commented
Can you use ```fmt``` in a cpp file? let the build deps have the fmt.

BTW. give a example to how to print a ```class``` by libfmt in a cpp file?

2023-04-07 01:54 UTC, wuhongsong commented
@Cyber-SiKu

2023-04-07 02:57 UTC, Cyber-SiKu requested changes

2023-04-07 02:57 UTC, Cyber-SiKu commented on WORKSPACE
> +    branch = "master",
Use a stable version? For example tag: 9.1.0.

2023-04-07 02:58 UTC, Cyber-SiKu commented
> Can you use `fmt` in a cpp file? let the build deps have the fmt.
> 
> BTW. give a example to how to print a `class` by libfmt in a cpp file?



agree! You can modify an old code as an example, or modify some unit tests.

2023-04-07 02:59 UTC, Cyber-SiKu commented
cicheck

2023-04-07 05:40 UTC, Cyber-SiKu commented
cicheck

2023-04-10 04:51 UTC, Tangruilin commented
> Can you use `fmt` in a cpp file? let the build deps have the fmt.
> 
> BTW. give a example to how to print a `class` by libfmt in a cpp file?

ok, i will do it these day

2023-04-24 01:28 UTC, Cyber-SiKu commented
@Tangruilin  Will you continue to follow up this PR?

2023-05-15 05:58 UTC, ilixiaocui commented
@Tangruilin Will you continue to follow up this PR?

2023-06-07 07:43 UTC, Cyber-SiKu commented
cicheck

2023-07-18 03:23 UTC, Cyber-SiKu commented
cicheck

2023-07-18 03:24 UTC, Cyber-SiKu commented
how to use:https://github.com/fmtlib/fmt/blob/master/README.rst

2023-07-18 03:24 UTC, Cyber-SiKu approved these changes

2023-07-18 07:35 UTC, Cyber-SiKu commented on WORKSPACE
> +    commit = "bce8d4ed087a0560492426f9f5be2713804daded"
miss `,`

2023-07-20 11:22 UTC, Cyber-SiKu commented
continue in [2635](https://github.com/opencurve/curve/pull/2635)

2023-07-20 11:22 UTC, closed without merging