[feat]tools-v2: add set availflag
opencurve/curve pull request #2455
Opened 2023-05-05 10:48 UTC by baytan0720

### What problem does this PR solve?

Issue Number: #2357  

Problem Summary: support set availflag command in [curve tool](https://github.com/opencurve/curve/tree/master/tools-v2)

### What is changed and how it works?

What's Changed:
add tools-v2/pkg/cli/command/curvebs/list/chunkserver/chunkserver.go
add tools-v2/pkg/cli/command/curvebs/list/unavailcopysets/unavailcopysets.go
add tools-v2/pkg/cli/command/curvebs/query/chunk/chunkinfo.go
add tools-v2/pkg/cli/command/curvebs/query/copyset/copyset_in_chunkserver.go
add tools-v2/pkg/cli/command/curvebs/set/set.go
tools-v2/pkg/cli/command/curvebs/set/copyset_availflag/copyset_availflag.go
modify tools-v2/internal/error/error.go
modify tools-v2/internal/utils/row.go
modify tools-v2/pkg/cli/command/curvebs/bs.go
modify tools-v2/pkg/config/bs.go

How it Works:
```
root@0ad49a8af612:/# curve bs set copyset-availflag -h               
Usage:  curve bs set copyset-availflag [flags]

set copyset availflag

Flags:
      --availflag             copysets available flag[required]
  -c, --conf string           config file (default is
                              $HOME/.curve/curve.yaml or
                              /etc/curve/curve.yaml)
      --dryrun                when dry run set true, no changes will be
                              made (default true)
  -f, --format string         output format (json|plain) (default "plain")
  -h, --help                  print help
      --mdsaddr string        mds address, should be like
                              127.0.0.1:6700,127.0.0.1:6701,127.0.0.1:6702
      --rpcretrytimes int32   rpc retry times (default 1)
      --rpctimeout duration   rpc timeout (default 10s)
      --showerror             display all errors in command
      --verbose               show some log

Examples:
$ curve bs set copyset-availflag --availflag=true --dryrun=false
```

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

2023-05-11 08:26 UTC, aspirer requested changes
we also need to update doc in `tools-v2/README.md`.

you can refer to pr #2465

2023-05-11 08:26 UTC, aspirer commented on tools-v2/internal/error/error.go
> +		return NewInternalCmdError(53, "get chunkserver in cluster fail, err: %s")
the errorno 53 is already used above, we should start with errorno 54.

2023-05-11 08:26 UTC, aspirer commented on tools-v2/pkg/cli/command/curvebs/update/copyset/availflag/availflag.go
> +	copysetAvailflagExample = `$ curve bs update copyset availflag --availflag=true --dryrun=false`
`set` or `update`?
you use `set` in conversation, I think it should be `update`, we should correct it.

2023-05-11 08:39 UTC, baytan0720 commented
> we also need to update doc in `tools-v2/README.md`.
> 
> you can refer to pr #2465

Ok, I will fix all. This pr is not ready yet. I've been a little busy lately.

2023-05-16 07:19 UTC, Cyber-SiKu commented on tools-v2/pkg/config/bs.go
> +	VIPER_CURVEBS_CHUNKSERVER_ADDRESS = "curvebs.csaddress"
```suggestion
	CURVEBS_CHUNKSERVER_ADDRESS       = "chunkserveraddr"
	VIPER_CURVEBS_CHUNKSERVER_ADDRESS = "curvebs.chunkserverAddr"
```

2023-05-16 07:19 UTC, Cyber-SiKu commented on tools-v2/pkg/cli/command/curvebs/list/chunkserver/chunkserver.go
> +	response *topology.GetChunkServerInClusterResponse
```suggestion
	ChunkServerInfos []*topology.ChunkServerInfo
```
is better?

2023-05-16 07:19 UTC, Cyber-SiKu commented on tools-v2/pkg/cli/command/curvebs/list/unavailcopysets/unavailcopysets.go
> +	response *topology.ListUnAvailCopySetsResponse
ditto

2023-05-16 07:19 UTC, Cyber-SiKu commented on tools-v2/pkg/cli/command/curvebs/query/chunk/chunkinfo.go
> + *  Copyright (c) 2022 NetEase Inc.
```suggestion
 *  Copyright (c) 2023 NetEase Inc.
```

2023-05-16 07:19 UTC, Cyber-SiKu commented on tools-v2/pkg/cli/command/curvebs/list/chunkserver/chunkserver.go
> + *  Copyright (c) 2022 NetEase Inc.
```suggestion
 *  Copyright (c) 2023 NetEase Inc.
```

2023-05-16 07:19 UTC, Cyber-SiKu commented on tools-v2/pkg/cli/command/curvebs/query/chunk/chunkinfo.go
> +			Info: &basecmd.Rpc{[]string{addressList[i]}, timeout, retrytimes, "GetChunkInfo"},
```suggestion
			Info: &basecmd.NewRpc{[]string{addressList[i]}, timeout, retrytimes, "GetChunkInfo"},
```

2023-05-16 07:19 UTC, Cyber-SiKu commented on tools-v2/pkg/cli/command/curvebs/update/copyset/availflag/availflag.go
> + *  Copyright (c) 2022 NetEase Inc.
```suggestion
 *  Copyright (c) 2023 NetEase Inc.
```

2023-05-16 07:19 UTC, Cyber-SiKu commented on tools-v2/pkg/cli/command/curvebs/update/copyset/availflag/availflag.go
> +/*
add use in readme

2023-06-02 16:58 UTC, baytan0720 commented
cicheck

2023-06-02 17:06 UTC, baytan0720 commented
cicheck

2023-06-05 07:42 UTC, Cyber-SiKu approved these changes

2023-06-05 07:44 UTC, SeanHai approved these changes

2023-06-05 07:44 UTC, merged