mds/tools: add set copyset available flag
opencurve/curve pull request #257
Opened 2021-02-04 12:21 UTC by bai-charisu

Change-Id: I0b1e2e85f11790194f8ddb040b387d9b0e4ea0f4

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

2021-02-19 07:30 UTC, ilixiaocui commented on src/mds/topology/topology_item.h
> +        available_(true) {}
mds启动从etcd中load进来的时候，该copyset的available状态没处理？

2021-02-19 08:45 UTC, bai-charisu commented on src/tools/copyset_check_core.cpp
> +    int majority = chunkserverLocation.size() / 2 + 1;
不会，下面的CheckHealthOnLeader里会判断副本数量是否小于3

2021-02-19 08:45 UTC, bai-charisu commented on src/tools/copyset_check.cpp
> +    int ret = 0;
因为res不再是int类型了

2021-02-19 09:08 UTC, bai-charisu commented on src/mds/topology/topology.cpp
> +        bool ret = storage_->UpdateCopySet(it->second);
done

2021-02-19 09:08 UTC, bai-charisu commented on src/mds/topology/topology_chunk_allocator.cpp
> +        if (!topology->GetCopySet(key, &csInfo)) {
done

2021-02-19 09:10 UTC, bai-charisu commented on src/mds/topology/topology_service.cpp
> +    LOG(INFO) << "Received request[log_id=" << cntl->log_id()
request是空的，下面打印了response，response中有copyset list

2021-02-19 09:10 UTC, bai-charisu commented on src/tools/copyset_check_core.h
> +    virtual CheckResult CheckOneCopyset(const PoolIdType& logicalPoolId,
done

2021-02-19 09:10 UTC, bai-charisu commented on src/mds/topology/topology_item.h
> +        available_(true) {}
已修改，加载和保存使用的是SerializeToString和ParseFromString

2021-02-19 10:52 UTC, ilixiaocui commented on src/mds/topology/topology_item.cpp
> +    available_ = data.availflag();
升级时候老版本是没有这个字段的，需要处理一下

2021-02-19 11:51 UTC, bai-charisu commented on src/mds/topology/topology.h
> +    virtual bool IsCopySetAvailable(CopySetKey key) const = 0;
去掉了

2021-02-19 11:51 UTC, bai-charisu commented on src/mds/topology/topology_chunk_allocator.cpp
> +    std::vector<CopysetIdInfo> *infos,
done

2021-02-19 11:51 UTC, bai-charisu commented on src/mds/topology/topology_item.cpp
> +    available_ = data.availflag();
done

2021-02-20 03:08 UTC, ilixiaocui approved these changes

2021-02-20 06:59 UTC, xu-chaojie commented on src/mds/topology/topology.cpp
> +        auto copysetInfo = it->second;
 这里要先拿copyset的写锁，再storage_->UpdateCopySet，否则这里会把别人对copyset的修改覆盖掉

2021-02-23 03:29 UTC, bai-charisu commented on src/mds/topology/topology.cpp
> +        auto copysetInfo = it->second;
done

2021-02-23 11:25 UTC, xu-chaojie requested changes

2021-02-23 11:25 UTC, xu-chaojie commented on src/mds/topology/topology.cpp
> +        WriteLockGuard wlockCopySet(v.GetRWLockRef());
这个地方改的不对，toUpdate里的copyset只是副本，这个锁起不了作用。

2021-03-01 10:39 UTC, bai-charisu commented
recheck

2021-03-02 12:46 UTC, xu-chaojie approved these changes

2021-03-03 01:49 UTC, merged