curvefs: recovey recyclebin file
opencurve/curve pull request #259
Opened 2021-02-08 06:01 UTC by SeanHai

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

2021-02-19 07:41 UTC, bai-charisu commented on src/mds/nameserver2/namespace_service.cpp
> +        request->filename() != recoverFileInfo.originalfullpathname()) {
originfullpathname在里面不是已经判断过了吗？怎么又判断一遍？

2021-02-19 07:41 UTC, bai-charisu commented on src/mds/nameserver2/namespace_service.cpp
> +    retCode = kCurveFS.CheckFileOwner(recoverFileName,
除了检查recoverfilename的owner，恢复后的filename的权限也需要检查一下

2021-02-19 07:41 UTC, bai-charisu commented on src/mds/nameserver2/curvefs.cpp
> +    auto ret1 = storage_->RecoverFile(recycleFileInfo, recoverFileInfo);
这里不能直接使用rename吗？

2021-02-19 08:03 UTC, SeanHai commented on proto/nameserver2.proto
> +    optional uint64     fileId = 5;
> fileId没看到在命令行里指定，什么时候会用到fileId？

现在是如果recyclebin中有多个同名删除的文件，则恢复最近删除的。这里fileId是留了个接口，如果后面需要恢复指定的文件（在多个同名文件情况下）可以使用。

2021-02-19 08:04 UTC, SeanHai commented on src/mds/nameserver2/namespace_service.cpp
> +        request->filename() != recoverFileInfo.originalfullpathname()) {
> originfullpathname在里面不是已经判断过了吗？怎么又判断一遍？

done

2021-02-19 08:14 UTC, SeanHai commented on src/mds/nameserver2/curvefs.cpp
> +    auto ret1 = storage_->RecoverFile(recycleFileInfo, recoverFileInfo);
> 这里不能直接使用rename吗？

功能是可以，就是语义没那么清晰，包括rename中打印日志中的oldfile、newfile，rename fail等

2021-02-19 08:56 UTC, cw123 requested changes

2021-02-19 08:56 UTC, cw123 commented on proto/nameserver2.proto
> +    // recover file status is BeingCloned
注释不对

2021-02-19 08:56 UTC, cw123 commented on src/client/mds_client.h
> +     * @param: id is inodeid，default 0，will not send to mds if not be set
id没有看到从哪里传进来

2021-02-19 08:56 UTC, cw123 commented on src/mds/nameserver2/curvefs.cpp
> +    // check the same file exists
参考rename做一些前置判断。根目录，相同的name

2021-02-19 08:56 UTC, cw123 commented on src/mds/nameserver2/namespace_service.cpp
> +StatusCode GetRecoverFileInfo(const std::string& originFileName,
这个逻辑放curvefs感觉更好一点

2021-02-19 08:56 UTC, cw123 commented on src/mds/nameserver2/curvefs.cpp
> +            if (fileInfo.owner() != owner &&
这里不应该用&&

2021-02-19 08:56 UTC, cw123 commented on src/mds/nameserver2/namespace_service.cpp
> +    FileWriteLockGuard guard(fileLockManager_, recoverFileName);
两个filename都要加锁，参考rename的加锁

2021-02-19 08:56 UTC, cw123 commented on src/mds/nameserver2/namespace_storage.cpp
> +StoreStatus NameServerStorageImp::RecoverFile(const FileInfo &recycleFInfo,
复用rename

2021-02-19 09:00 UTC, SeanHai commented on src/mds/nameserver2/namespace_service.cpp
> +    retCode = kCurveFS.CheckFileOwner(recoverFileName,
> 除了检查recoverfilename的owner，恢复后的filename的权限也需要检查一下

done

2021-02-19 09:01 UTC, SeanHai commented on curvefs_python/curvefs_wrap.cxx
> +   { (char *)"Recover", _wrap_Recover, METH_VARARGS, NULL},
> 保持对齐

done

2021-02-19 09:02 UTC, SeanHai commented on curvefs_python/curvefs_wrap.cxx
> +   { (char *)"CBDClient_Recover", _wrap_CBDClient_Recover, METH_VARARGS, NULL},
> 保持对齐

done

2021-02-19 09:05 UTC, SeanHai commented on proto/nameserver2.proto
> +    // recover file status is BeingCloned
> 注释不对

done

2021-02-19 09:22 UTC, SeanHai commented on src/mds/nameserver2/namespace_service.cpp
> +    FileWriteLockGuard guard(fileLockManager_, recoverFileName);
> 两个filename都要加锁，参考rename的加锁

done

2021-02-19 09:25 UTC, SeanHai commented on src/mds/nameserver2/namespace_storage.cpp
> +StoreStatus NameServerStorageImp::RecoverFile(const FileInfo &recycleFInfo,
> 复用rename

done

2021-02-19 11:52 UTC, SeanHai commented on src/mds/nameserver2/curvefs.cpp
> +            if (fileInfo.owner() != owner &&
> 这里不应该用&&

done, 新增CheckRecycleFileOwner

2021-02-20 01:54 UTC, SeanHai commented on src/mds/nameserver2/namespace_service.cpp
> +StatusCode GetRecoverFileInfo(const std::string& originFileName,
> 这个逻辑放curvefs感觉更好一点

done

2021-02-20 02:24 UTC, SeanHai commented on src/mds/nameserver2/curvefs.cpp
> +    // check the same file exists
> 参考rename做一些前置判断。根目录，相同的name

前置判断在NameSpaceService::RecoverFile中做了，主要是检查originFileName的合法性（IsPathValid），如果是根目录也是合法的，但是在recycleBin中找对应文件信息时会失败

2021-02-22 01:57 UTC, SeanHai commented on proto/nameserver2.proto
> +    optional uint64     fileId = 5;
> fileId没看到在命令行里指定，什么时候会用到fileId？

原本是如果recyclebin中有多个同名删除的文件，则恢复最近删除的，这里fileId是留了个接口。这次review修改实现了--id选项（可选）来恢复指定文件。

2021-02-22 01:58 UTC, SeanHai commented on src/mds/nameserver2/curvefs.cpp
> +    auto ret1 = storage_->RecoverFile(recycleFileInfo, recoverFileInfo);
> 这里不能直接使用rename吗？

done

2021-02-22 01:58 UTC, SeanHai commented on src/client/mds_client.h
> +     * @param: id is inodeid，default 0，will not send to mds if not be set
> id没有看到从哪里传进来

原本是如果recyclebin中有多个同名删除的文件，则恢复最近删除的，这里fileId是留了个接口。这次review修改实现了--id选项（可选）来恢复指定文件。

2021-02-22 03:28 UTC, cw123 requested changes

2021-02-22 03:28 UTC, cw123 commented on src/mds/nameserver2/curvefs.cpp
> +    const std::string recoverDir = "/RecycleBin";
不要硬编码

2021-02-22 03:28 UTC, cw123 commented on src/mds/nameserver2/curvefs.cpp
> +        LOG(ERROR) << "WalkPath failed, the middle path of "
慎重使用ERROR级别的打印。只有需要电话告警的错误才需要ERROR打印，检查下这次commit中的所有ERROR打印是否必要。

2021-02-22 03:28 UTC, cw123 commented on src/mds/nameserver2/namespace_service.cpp
> +
destination 需要check isPathValid
RecycleFile和destination 需要共同check，参考IsRenamePathValid。

2021-02-22 03:28 UTC, cw123 commented on src/mds/nameserver2/namespace_service.cpp
> +    retCode = kCurveFS.GetRecoverFileInfo(request->filename(),
这里是否需要先加一小段的读锁，再考虑一下

2021-02-22 03:34 UTC, SeanHai commented on src/mds/nameserver2/curvefs.cpp
> +    const std::string recoverDir = "/RecycleBin";
> 不要硬编码

done

2021-02-22 05:54 UTC, SeanHai commented on src/mds/nameserver2/curvefs.cpp
> +        LOG(ERROR) << "WalkPath failed, the middle path of "
> 慎重使用ERROR级别的打印。只有需要电话告警的错误才需要ERROR打印，检查下这次commit中的所有ERROR打印是否必要。

done

2021-02-22 05:58 UTC, bai-charisu commented on src/mds/nameserver2/curvefs.cpp
> +StatusCode CurveFS::CheckRecycleFileOwner(const std::string &filename,
为什么要增加这个函数，以前的FileOwner函数不能直接用吗

2021-02-22 05:58 UTC, bai-charisu commented on src/mds/nameserver2/namespace_service.cpp
> +    retCode = kCurveFS.CheckDestinationOwner(
同上，为什么不能统一使用CheckFileOwner

2021-02-22 06:04 UTC, SeanHai commented on src/mds/nameserver2/curvefs.cpp
> +StatusCode CurveFS::CheckRecycleFileOwner(const std::string &filename,
> 为什么要增加这个函数，以前的FileOwner函数不能直接用吗

因为原来的检查fileowner需要保证目标文件和上层目录的owner都是相同的，但是恢复recyclebin文件时，recyclebin目录的owner是root，里面的文件owner可以是其他的

2021-02-22 06:20 UTC, SeanHai commented on src/mds/nameserver2/namespace_service.cpp
> +    retCode = kCurveFS.CheckDestinationOwner(
> 同上，为什么不能统一使用CheckFileOwner

CheckFileOwner 在检查文件owner时如果文件不存在则返回失败，CheckDestinationOwner和CheckFileOwner的区别是当文件不存在时返回成功（recover、rename等目的文件应该是不存在的，只检查上层路径owner即可）

2021-02-22 07:50 UTC, SeanHai commented on src/mds/nameserver2/namespace_service.cpp
> +
> destination 需要check isPathValid
> RecycleFile和destination 需要共同check，参考IsRenamePathValid。

destination应该不用检查吧，因为恢复后的路径是从fileInfo中获得的（创建时已经处理过了），并且应该不会出现互相包含路径的情况，因为destiantion路径不会包含/RecycleBin

2021-02-22 08:40 UTC, cw123 commented on src/mds/nameserver2/namespace_service.cpp
> +
如果是/a/RecycleBin，也会有问题

2021-02-22 09:24 UTC, SeanHai commented on src/mds/nameserver2/namespace_service.cpp
> +    retCode = kCurveFS.GetRecoverFileInfo(request->filename(),
> 这里是否需要先加一小段的读锁，再考虑一下

done

2021-02-22 10:51 UTC, SeanHai commented on src/mds/nameserver2/namespace_service.cpp
> +
> 如果是/a/RecycleBin，也会有问题

实际测试了 /a/RecycleBin(或/a/RecycleBin/file1) 也没问题，因为rename那应该主要是检查出现目录包含后获取锁的问题，而recover场景下， /a/RecycleBin/file 和 /RecycleBin/file 并不是目录包含关系

2021-02-23 02:13 UTC, bai-charisu commented on src/mds/nameserver2/namespace_service.cpp
> +    retCode = kCurveFS.CheckDestinationOwner(
那这个不需要，你只需要把路径里的上层目录传给CheckFileOwner就可以了吧。

2021-02-23 02:17 UTC, bai-charisu approved these changes

2021-02-23 11:17 UTC, cw123 requested changes

2021-02-23 11:17 UTC, cw123 commented on src/mds/nameserver2/namespace_service.cpp
> +        FileReadLockGuard guard(fileLockManager_, RECYCLEBINDIR);
不是对这个文件加锁RECYCLEBINDIR

2021-02-23 11:17 UTC, cw123 commented on src/mds/nameserver2/namespace_service.cpp
> +        FileReadLockGuard guard(fileLockManager_, RECYCLEBINDIR);
request->filename()

2021-02-23 11:30 UTC, cw123 approved these changes

2021-02-23 11:31 UTC, SeanHai commented on src/mds/nameserver2/namespace_service.cpp
> +        FileReadLockGuard guard(fileLockManager_, RECYCLEBINDIR);
> request->filename()

这个request->filename 是删除前的文件名，这个文件是不存在的，这个是根据删除前的文件名去recyclebin找现在在recyclebin中对应的删除后的文件信息

2021-02-23 11:42 UTC, ilixiaocui approved these changes

2021-02-23 11:42 UTC, merged