fix bs check server
opencurve/curve pull request #2626
Opened 2023-07-16 08:02 UTC by caoxianfei1

Signed-off-by: pengpengSir <2968332764@qq.com>

fix bs check server

Signed-off-by: pengpengSir <2968332764@qq.com>

seperate command

Signed-off-by: pengpengSir <2968332764@qq.com>

Update server.go

Signed-off-by: pengpengSir <82749014+pengpengSir@users.noreply.github.com>

[tools-v2] add bs check server

### What problem does this PR solve?

Issue Number: #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

2023-07-16 08:03 UTC, caoxianfei1 commented
cicheck

2023-07-16 15:29 UTC, montaguelhz requested changes
good job

2023-07-16 15:29 UTC, montaguelhz commented on tools-v2/internal/error/error.go
> +		return NewInternalCmdError(55, "get chunkserver infos fail, err: %s")
The number is 71 now.

2023-07-16 15:29 UTC, montaguelhz commented on tools-v2/pkg/cli/command/curvebs/check/server/server.go
> +	// 这里就可以得到指定的server下的所有的chunkserver
Maybe should put comments translated into English.

2023-07-16 15:29 UTC, montaguelhz commented on tools-v2/pkg/cli/command/curvebs/check/server/server.go
> +	// 需要遍历所有的chunkserver下的copyset,获取copyset的健康情况
ditto

2023-07-16 15:29 UTC, montaguelhz commented on tools-v2/pkg/cli/command/curvebs/check/server/server.go
> +		// 得到对应的chunkserver下面的所有的copyset info
ditto

2023-07-16 15:29 UTC, montaguelhz commented on tools-v2/pkg/cli/command/curvebs/check/server/server.go
> +			// sCmd.Cmd.ParseFlags([]string{
remove unused code.

2023-07-16 15:29 UTC, montaguelhz commented on tools-v2/pkg/cli/command/curvebs/list/chunkserver/chunkserver.go
> +		return fmt.Errorf("flag --%s and -- %s cannot be used together",
There's an extra space.

2023-07-25 02:51 UTC, caoxianfei1 commented on tools-v2/internal/error/error.go
> +		return NewInternalCmdError(55, "get chunkserver infos fail, err: %s")
fixed

2023-07-25 02:52 UTC, closed without merging