curve-ansible: add ping.yml to check ssh connection
opencurve/curve pull request #267
Opened 2021-02-25 12:33 UTC by SeanHai

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

2021-03-01 06:25 UTC, bai-charisu approved these changes

2021-03-02 07:30 UTC, cw123 requested changes

2021-03-02 07:30 UTC, cw123 commented on curve-ansible/common_tasks/ping.yml
> +---
这个放到common_tasks目录，怎么调用

2021-03-02 07:46 UTC, SeanHai commented on curve-ansible/common_tasks/ping.yml
> +---
> 这个放到common_tasks目录，怎么调用

这个也是在申请机器权限后（主要是client）判断是否获得了对应的ssh权限，目前也是属于前置工作中，单独使用：ansible-playbook ping.yml -i client.ini。 可以方法curve-ansible目录下

2021-03-02 07:46 UTC, SeanHai commented on curve-ansible/common_tasks/ping.yml
> +---
> playbook要放到curve-ansible目录，common_tasks是放task的

done

2021-03-02 08:22 UTC, bai-charisu approved these changes

2021-03-02 09:22 UTC, cw123 approved these changes

2021-03-02 11:11 UTC, ilixiaocui approved these changes

2021-03-02 11:11 UTC, merged