Curvebs stop volume snapshot
opencurve/curve pull request #2780
Opened 2023-09-27 11:25 UTC by ZackSoul

### What problem does this PR solve?

Issue Number: #2579 

Problem Summary:

### What is changed and how it works?
add curve bs stop volume snapshot

What's Changed:

How it Works:
curve bs stop volume volumeSnapshot

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

2023-09-28 02:58 UTC, Cyber-SiKu commented
pls fix dco

2023-09-28 05:50 UTC, Cyber-SiKu reviewed
add in readme

2023-10-08 02:04 UTC, ZackSoul commented
Keep reviewing？Please.

2023-10-08 02:52 UTC, Cyber-SiKu requested changes

2023-10-08 02:52 UTC, Cyber-SiKu commented on tools-v2/pkg/config/bs.go
> +func AddBsSnapshotSeqIDOptionFlag(cmd *cobra.Command) {
is optional or required?

2023-10-08 02:52 UTC, Cyber-SiKu commented on tools-v2/pkg/cli/command/curvebs/stop/volumeSnapshot/volumeSnapshot.go
> +			item.Result = cobrautil.ROW_VALUE_FAILED
Refer to the error output of the original tool, please enrich it.

2023-10-08 02:52 UTC, Cyber-SiKu commented on tools-v2/pkg/cli/command/curvebs/stop/volumeSnapshot/volumeSnapshot.go
> +	sCmd.Error = cmderror.Success()
Is it a success if a deletion error occurs?

2023-10-08 02:52 UTC, Cyber-SiKu commented on tools-v2/pkg/cli/command/curvebs/stop/volumeSnapshot/stop_volume.go
> +	offset  = "0"
capital

2023-10-08 02:52 UTC, Cyber-SiKu commented on tools-v2/pkg/cli/command/curvebs/stop/volumeSnapshot/stop_volume.go
> +		fmt.Printf("get snapshot list fail, error=%s\n", err)
Try not to output errors in the middle, but return an error, cmdError, etc.
You can refer to the implementation of other commands

2023-10-10 02:03 UTC, ZackSoul commented on tools-v2/pkg/config/bs.go
> +func AddBsSnapshotSeqIDOptionFlag(cmd *cobra.Command) {
optional

2023-10-10 02:14 UTC, Cyber-SiKu approved these changes

2023-10-10 02:15 UTC, Cyber-SiKu commented on tools-v2/pkg/config/bs.go
> +
This value should be required, right?

2023-10-10 03:58 UTC, ZackSoul commented
cicheck

2023-10-10 07:36 UTC, ZackSoul commented
cicheck

2023-10-10 08:20 UTC, ZackSoul commented
cicheck

2023-10-10 08:22 UTC, ZackSoul commented
cicheck

2023-10-10 08:26 UTC, ZackSoul commented
cicheck

2023-10-10 08:28 UTC, ZackSoul commented
cicheck

2023-10-10 08:29 UTC, ZackSoul commented
cicheck

2023-10-11 02:21 UTC, Cyber-SiKu commented
fix conflicts & dco

2023-10-12 10:07 UTC, ZackSoul commented
cicheck

2023-10-17 08:24 UTC, closed without merging