ansible: improve daemon restart
opencurve/curve pull request #315
Opened 2021-04-15 02:17 UTC by SeanHai

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

2021-04-15 07:53 UTC, ilixiaocui commented on curve-ansible/roles/restart_service/tasks/include/restart_nebd.yml
> +- name: restart nebd-server with daemon
Why not reuse the above restart module

2021-04-15 08:10 UTC, cw123 requested changes

2021-04-15 08:10 UTC, cw123 commented on curve-ansible/common_tasks/restart_service.yml
> +    - name: stop service without daemon
这里需要wait until server is down吗？

2021-04-15 09:05 UTC, SeanHai commented on curve-ansible/roles/restart_service/tasks/include/restart_nebd.yml
> +- name: restart nebd-server with daemon
> Why not reuse the above restart module

done

2021-04-15 12:41 UTC, SeanHai commented on curve-ansible/common_tasks/restart_service.yml
> +    - name: stop service without daemon
> Is here need wait until server is down？

done

2021-04-16 03:39 UTC, ilixiaocui approved these changes

2021-04-16 05:52 UTC, cw123 approved these changes

2021-04-16 05:55 UTC, merged