curvefs: add default permission check
opencurve/curve pull request #497
Opened 2021-08-10 11:55 UTC by SeanHai

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

2021-08-11 07:49 UTC, xu-chaojie requested changes

2021-08-11 07:49 UTC, xu-chaojie commented on curvefs/src/client/main.c
> +    // add default_permissions and allow_other
这个地方不要这么改，改到启动脚本里面去，或者在下面的opts中直接设置默认值比较好

2021-08-11 08:05 UTC, SeanHai commented on curvefs/src/client/main.c
> +    // add default_permissions and allow_other
> It will be better to add "default_permissions" and "allow_other" in the startup script or add these default option in the "opts" below.

fixed

2021-08-11 08:07 UTC, xu-chaojie approved these changes

2021-08-12 02:52 UTC, wu-hanqing approved these changes

2021-08-12 03:15 UTC, merged