zeroize memory copy
opencurve/curve pull request #78
Opened 2020-08-28 02:12 UTC by wu-hanqing

Change-Id: I2d389b24446623e8f639642a2b354120f20dbe56

### What problem does this PR solve?

Issue Number: None

Problem Summary:

### What is changed and how it works?

What's Changed: zeroize memory copy between nebd and curve-client

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [x] I acknowledge that all my contributions will be made under the project's license

2020-09-18 09:34 UTC, wu-hanqing commented on src/client/io_tracker.cpp
> +        this, mc_, &reqlist_, nullptr, offset_, length_, mdsclient, fi);
修改之前的splitor，需要传入用户buffer，拆分的sub-io的buffer会指向用户buffer不同的offset。
- 写请求会把sub-io的buffer中的数据复制到rpc controller中。
- 读请求读到的数据，会从rpc controller复制到sub-io的buffer中。这里当所有的sub-io完成后，用户buffer里面就存储了需要读取的数据。

修改之后，小io的buffer，改成了IOBuf。
- 写请求，需要把用户IOBuf中的内容cut到sub-io的iobuf中，然后传给rpc controller。
- 读请求，只需要把rpc controller中的iobuf复制给sub-io的iobuf中就可以了。当所有sub-io完成后，会把所有sub-io的iobuf按顺序拼接到一起，返回给用户。

2020-09-21 05:55 UTC, wu-hanqing commented on include/client/libcurve.h
> +    virtual int AioRead(int fd, CurveAioContext* aioctx, UserDataType dataType);
这个只是个枚举类型，没有必要加。

2020-09-21 06:02 UTC, wu-hanqing commented on src/client/client_common.cpp
> -const char* OpTypeToString(OpType optype) {
这个文件就一个函数，而且函数逻辑不复杂，就改成inline放到头文件了。

2020-09-21 06:03 UTC, wu-hanqing commented on src/client/iomanager4chunk.cpp
> +    temp->SetUserDataType(UserDataType::RawBuffer);
这里是直接读快照chunk，接口传入的是char* buf。

2020-09-21 06:06 UTC, wu-hanqing commented on src/client/iomanager4file.cpp
> +    memcpy(buf, data.to_string().c_str(), length);
需要零拷贝的只有nebd使用的接口。上层nbd/qemu都是使用的异步读写接口，所以同步这里就没修改了。

2020-09-21 06:07 UTC, wu-hanqing commented on include/client/libcurve.h
> +    virtual int AioRead(int fd, CurveAioContext* aioctx, UserDataType dataType);
这个只是个枚举类型，没有必要加。

2020-09-21 06:07 UTC, wu-hanqing commented on include/client/libcurve.h
> +    virtual int AioRead(int fd, CurveAioContext* aioctx, UserDataType dataType);
这个只是个枚举类型，没有必要加。

2020-09-21 12:10 UTC, bai-charisu approved these changes

2020-09-22 02:11 UTC, xu-chaojie approved these changes

2020-09-22 08:19 UTC, xu-chaojie requested changes

2020-09-22 08:19 UTC, xu-chaojie commented on nebd/src/part2/file_service.cpp
>          doneGuard.release();
上面这个buf.release(); 不如在这里做，这样上面不需要 delete reinterpret_cast<butil::IOBuf*>(aioContext->buf); 或者直接跟read一样

2020-09-22 11:54 UTC, wu-hanqing commented on src/client/file_instance.cpp
> +    return iomanager4file_.AioRead(aioctx, mdsclient_, dataType);
同步请求在最外层封装比较方便，因为函数一路调进去，到返回的时候，可以直接从iobuf转成char*，然后返回给用户。
异步请求完成返回的地方需要把读取的请求，从iobuf转成char*，这里就需要对context或者callback做一次封装。在异步请求完成后，调用用户callback之前进行转换。
现在的改动是在IOTracker这层做了转换，IOTracker以下，都是用iobuf来传递的。需要参数的也就两三层。这个可以后续再进行改动。

2020-09-23 06:05 UTC, xu-chaojie approved these changes

2020-09-23 07:04 UTC, wu-hanqing commented on src/client/io_tracker.cpp
> +    DVLOG(9) << "aiowrite op, offset = " << offset << ", length = " << length;
Done

2020-09-23 09:18 UTC, merged