optimize curve-client
opencurve/curve pull request #88
Opened 2020-09-08 06:51 UTC by wu-hanqing

### What problem does this PR solve?

optimization curve-client performance

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

2020-09-14 02:49 UTC, bai-charisu commented on src/client/request_closure.h
> +     * 获取metric指针
新加的注释最好都是英文

2020-09-14 06:07 UTC, wu-hanqing commented on src/common/concurrent/task_thread_pool.cpp
>  namespace common {
Done

2020-09-14 06:07 UTC, wu-hanqing commented on src/client/chunk_closure.cpp
> -ClientClosure::BackoffParam  ClientClosure::backoffParam_;
没有去掉，应该是github显示的问题

2020-09-14 06:07 UTC, wu-hanqing commented on src/client/request_closure.h
> +     * 获取metric指针
这部分注释不是新加的，是调整了一些函数的顺序。

2020-09-14 06:09 UTC, wu-hanqing commented on src/client/libcurve_file.cpp
> +    FileInstance* fileserv = FileInstance::NewInitedFileInstance(
使用上没啥区别，改成放到FileInstance类里面了。

2020-09-22 12:48 UTC, xu-chaojie requested changes

2020-09-22 12:48 UTC, xu-chaojie commented on src/client/client_common.h
>  typedef struct ChunkIDInfo {
typedef 也可以去掉

2020-09-22 12:48 UTC, xu-chaojie commented on src/client/chunk_closure.h
> +        chunkinforesponse_.reset(static_cast<GetChunkInfoResponse*>(message));
保存Response 用std::unique_ptr<Message> 基类的智能指针去存好了，这里不需要重写

2020-09-22 12:48 UTC, xu-chaojie commented on src/client/chunk_closure.h
这个也不需要

2020-09-22 12:48 UTC, xu-chaojie commented on src/client/chunk_closure.cpp
> +    RequestClosure *reqDone = static_cast<RequestClosure *>(done_);
dynamic_cast 对类型做了一定的校验，这里不要改成static_cast吧，应该使用越精确的cast越好，尽量做更小的类型转换

2020-09-22 12:48 UTC, xu-chaojie commented on src/client/chunk_closure.cpp
> +    reqDone_ = static_cast<RequestClosure*>(done_);
同上

2020-09-23 03:34 UTC, xu-chaojie requested changes

2020-09-23 03:34 UTC, xu-chaojie commented on src/client/unstable_helper.cpp
> +    if (ret.second && unstabled == option_.serverUnstableThreshold) {
unstabled == option_.serverUnstableThreshold  这里=而不是 > 是为了只让刚好到达阈值的那个线程返回ServerUnstable?

2020-09-23 03:34 UTC, xu-chaojie commented on src/client/unstable_helper.h
> +        serverUnstabledChunkservers_[ip].erase(csId);
这个serverunstable是为了应对server挂掉这种情况吗？ 如果是，那么这里是否可以clear  整个serverUnstabledChunkservers_， 因为既然有一个chunkserver正常的请求了，那么意味着整个server应该没挂？

2020-09-23 12:14 UTC, wu-hanqing commented on src/client/chunk_closure.cpp
> +    reqDone_ = static_cast<RequestClosure*>(done_);
这里其实能确定是这个类型，所以没必要用dynamic_cast

2020-09-23 12:14 UTC, wu-hanqing commented on src/client/chunk_closure.h
上面一个SetResponse是可以去掉的，这个需要保留。
这个请求和其他请求的Response是不同的类型，而且都需要获取response里面的statuscode。
基类没有获取status的虚函数，所以还是转换到具体的子类，然后返回statuscode。上面一个暂时不修改了。

2020-09-23 12:14 UTC, wu-hanqing commented on src/client/client_common.h
>  typedef struct ChunkIDInfo {
这个文件里的typedef去掉后，快照相关的单元测试有问题，暂时先保留吧。

2020-09-23 12:14 UTC, wu-hanqing commented on src/client/iomanager.h
>      static Atomic<uint64_t>   idRecorder_;
Done

2020-09-23 12:14 UTC, wu-hanqing commented on src/client/unstable_helper.cpp
> +    if (ret.second && unstabled == option_.serverUnstableThreshold) {
是的，这里限制了只触发一次server unstable。如果不限制，在chunkserver和mds同时宕机的情况下，server unstable会去mds获取server上的chunkserver列表，导致bthread线程被沾满。

2020-09-23 12:15 UTC, wu-hanqing commented on src/client/unstable_helper.h
> +        serverUnstabledChunkservers_[ip].erase(csId);
Done

2020-09-23 12:16 UTC, wu-hanqing commented on src/client/chunk_closure.cpp
> +    RequestClosure *reqDone = static_cast<RequestClosure *>(done_);
这里其实能确定是这个类型，所以没必要用dynamic_cast

2020-09-23 12:16 UTC, wu-hanqing commented on nebd/src/part1/nebd_client.h
> +            bthread::execution_queue_execute(rpcTaskQueues_[dist(gen)], task);
Done

2020-09-23 12:16 UTC, wu-hanqing commented on nebd/src/part1/nebd_client.cpp
> +    LOG_IF(WARNING, ret != true)
Done

2020-09-24 02:17 UTC, xu-chaojie commented on src/client/unstable_helper.h
> +        serverUnstabledChunkservers_[ip].erase(csId);
clear serverUnstabledChunkservers_ 后，但是timeoutTimes_中其他ip的没有清理，会不会造成逻辑问题？

2020-09-24 02:34 UTC, xu-chaojie approved these changes

2020-09-24 02:35 UTC, merged