support wal covered writing
opencurve/curve pull request #92
Opened 2020-09-15 08:35 UTC by bai-charisu

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

2020-09-22 02:57 UTC, ilixiaocui commented on curve-ansible/deploy_chunkserver.yml
> +- name: prepare chunkserver
为啥在这里有一个单独的deploy_chunkserver.yml? 之前不是直接放在deploy_curve.yml里的？

2020-09-22 02:59 UTC, ilixiaocui commented on curve-ansible/roles/install_package/tasks/include/copy_file_to_remote.yml
> +  when: copy_file_res.failedss
笔误？

2020-09-22 03:32 UTC, ilixiaocui commented on curve-ansible/roles/install_package/templates/chunkserver_ctl.sh.j2
> +    echo "    deploy one wal pool                 : ./chunkserver_ctl.sh deploy-wal-pool {\$chunkserverId}"
没有deploy all chunkfile pool 和 deploy one chunkfilepool吗

2020-09-22 06:03 UTC, ilixiaocui commented on src/chunkserver/chunk_closure.h
加在下面成员变量中

2020-09-22 06:12 UTC, ilixiaocui commented on deploy/local/chunkserver/conf/chunkserver.conf.0
> +walfilepool.meta_file_size=4096
meta_file_size 和 metapage_size 有啥区别

2020-09-22 06:22 UTC, ilixiaocui commented on src/chunkserver/op_request.cpp
> +static bvar::LatencyRecorder g_oprequest_writechunk_latency(
临时的metric先去掉吧

2020-09-22 07:01 UTC, ilixiaocui commented on src/chunkserver/raftlog/curve_segment.h
> +friend class butil::RefCountedThreadSafe<CurveSegment>;
不对齐

2020-09-22 08:21 UTC, ilixiaocui commented on src/fs/ext4_filesystem_impl.cpp
> +static bvar::LatencyRecorder g_fs_write_latency(
临时的metric先去掉吧

2020-09-23 02:24 UTC, bai-charisu commented on curve-ansible/deploy_chunkserver.yml
> +- name: prepare chunkserver
自己写的临时程序忘删了，已删掉

2020-09-23 02:24 UTC, bai-charisu commented on curve-ansible/roles/install_package/tasks/include/copy_file_to_remote.yml
> +  when: copy_file_res.failedss
done

2020-09-23 02:25 UTC, bai-charisu commented on curve-ansible/roles/install_package/templates/chunkserver_ctl.sh.j2
> +    echo "    deploy one wal pool                 : ./chunkserver_ctl.sh deploy-wal-pool {\$chunkserverId}"
目前没有场景需要提供单独的格式化chunfile pool的命令

2020-09-23 02:25 UTC, bai-charisu commented on src/chunkserver/chunk_closure.h
这个是用来计算metric的，不再需要，已去掉

2020-09-23 02:27 UTC, bai-charisu commented on deploy/local/chunkserver/conf/chunkserver.conf.0
> +walfilepool.meta_file_size=4096
meta_file_size是记录元数据文件的大小，元数据文件是格式化之后存放pool的目录，file_size，meta_size这些元数据的。
metapage_size是头部的meta page的大小，也是内存对齐的单位

2020-09-23 02:27 UTC, bai-charisu commented on src/chunkserver/op_request.cpp
> +static bvar::LatencyRecorder g_oprequest_writechunk_latency(
done

2020-09-23 02:27 UTC, bai-charisu commented on src/chunkserver/raftlog/curve_segment.h
> +friend class butil::RefCountedThreadSafe<CurveSegment>;
done

2020-09-23 02:27 UTC, bai-charisu commented on src/fs/ext4_filesystem_impl.cpp
> +static bvar::LatencyRecorder g_fs_write_latency(
done

2020-09-23 13:12 UTC, xu-chaojie requested changes

2020-09-23 13:12 UTC, xu-chaojie commented on src/chunkserver/raftlog/curve_segment.cpp
> +        if (braft::FLAGS_raft_sync && will_sync && FLAGS_enableWalDirectWrite) {
不enableWalDirectWrite就不sync了？

2020-09-24 03:27 UTC, bai-charisu commented on deploy/local/chunkserver/conf/chunkserver.conf.0
>  chunkfilepool.retry_times=5
接口测试要用的

2020-09-24 03:27 UTC, bai-charisu commented on src/chunkserver/raftlog/curve_segment_log_storage.cpp
> +        uint32_t maxTotalFileSize = kWalFilePool->GetFilePoolOpt().fileSize
不可以作为CurveSegmentLogStorage的初始化参数，因为LogStorage的初始化时braft代码里做的，只有path一个参数

2020-09-24 06:41 UTC, bai-charisu commented on src/chunkserver/raftlog/curve_segment_log_storage.cpp
> +            if (_open_segment->close() == 0) {
done

2020-09-24 06:42 UTC, bai-charisu commented on src/chunkserver/raftlog/curve_segment_log_storage.cpp
> +                    return -1;
done

2020-09-24 06:42 UTC, bai-charisu commented on src/chunkserver/raftlog/define.h
> +const size_t kBraftEntryHeaderSize = 24;
sizof(CurveSegment::EntryHeader)会按照8字节对齐，是32不是28，braft里面就是这样写的，沿用这种方式吧

2020-09-24 06:43 UTC, bai-charisu commented on src/chunkserver/raftlog/curve_segment.cpp
> +        ::close(_fd);
这部分去掉了，CurveSegment不需要知道文件长度

2020-09-24 06:43 UTC, bai-charisu commented on src/chunkserver/raftlog/curve_segment.cpp
> +                            header_size + header.data_real_len) != 0) {
旧entry的部分去掉了

2020-09-24 06:43 UTC, bai-charisu commented on src/chunkserver/raftlog/curve_segment.h
> +        if (_from_pool) {
done

2020-09-24 06:43 UTC, bai-charisu commented on src/chunkserver/raftlog/curve_segment.cpp
> +    if (to_write % _meta_page_size != 0) {
done，定义了一个新的flag walAlignSize

2020-09-24 06:44 UTC, bai-charisu commented on src/chunkserver/raftlog/curve_segment.cpp
> +        if (braft::FLAGS_raft_sync && will_sync && FLAGS_enableWalDirectWrite) {
写错了，应该是如果enableWalDirectWrite就不sync，direct模式不需要调用sync

2020-09-24 08:17 UTC, bai-charisu commented on src/chunkserver/raftlog/curve_segment_log_storage.cpp
> +                scoped_refptr<Segment> prev_open_segment;
braft::segment是用scoped_refptr管理的，把析构函数定义成了私有的，只有scope ptr能够访问

2020-09-24 08:54 UTC, bai-charisu commented on src/chunkserver/raftlog/curve_segment_log_storage.cpp
> +    if (index < first_index || index > last_index + 1) {
这个是为了把index=last_index+1单独处理，不打日志。replicator复制日志的时候会逐渐增加index去get_entry，直到即将发送的entry数量超过最大值或者get_entry返回失败。所以index=last_index+1是每次循环结束的条件，不用打日志。

2020-09-24 10:30 UTC, xu-chaojie approved these changes

2020-09-24 10:30 UTC, merged