change client log level
opencurve/curve pull request #94
Opened 2020-09-17 02:58 UTC by wu-hanqing

### What problem does this PR solve?

Problem Summary: Change some client log level

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

2020-09-18 08:28 UTC, bai-charisu commented on src/client/lease_executor.cpp
> +        LOG(ERROR) << "Refresh session auth fail, block io. "
这个怎么改成error了？

2020-09-18 08:28 UTC, bai-charisu commented on src/client/lease_executor.cpp
> +        LOG(ERROR) << "session or file not exists, no longer refresh!"
还有这个

2020-09-18 08:28 UTC, bai-charisu commented on src/client/lease_executor.cpp
> +        LOG(ERROR) << "session or file not exists, no longer refresh!"
还有这个

2020-09-18 08:28 UTC, bai-charisu commented on src/client/libcurve_file.cpp
> +        LOG_IF(ERROR, ret != LIBCURVE_ERROR::OK)
这里打ERROR的话不是还会报警吗

2020-09-18 08:37 UTC, wu-hanqing commented on src/client/lease_executor.cpp
> +        LOG(ERROR) << "Refresh session auth fail, block io. "
这个和下面的一个ERROR正常不会出现，如果出现了是一定有问题了。所以这两处改成了ERROR。

2020-09-18 08:38 UTC, wu-hanqing commented on src/client/lease_executor.cpp
> +        LOG(ERROR) << "session or file not exists, no longer refresh!"
这个需要修改一下，把rpc failed的情况去掉。

2020-09-18 08:39 UTC, wu-hanqing commented on src/client/libcurve_file.cpp
> +        LOG_IF(ERROR, ret != LIBCURVE_ERROR::OK)
这部分改动是把mds-client里面的error都去掉了。由调用方根据返回值来确定是否需要打日志。

2020-09-18 09:08 UTC, wu-hanqing commented on src/client/libcurve_file.cpp
> +        LOG_IF(ERROR, ret != LIBCURVE_ERROR::OK)
这里的改动是把mds_client里面的error日志都去掉了。由调用方根据返回值来决定是否打印。
这里加上error，是因为这些控制面都是用户调用的接口，而且mds_client返回的错误，会直接返回给用户。

2020-09-18 11:14 UTC, bai-charisu approved these changes

2020-09-21 07:23 UTC, xu-chaojie requested changes

2020-09-21 07:23 UTC, xu-chaojie commented on src/client/chunk_closure.cpp
> +    LOG_EVERY_SECOND(WARNING) << OpTypeToString(reqCtx_->optype_)
这里改成warning是为啥?是否client出现超时也不报警了？ 还有如果是超时以外的错误是否需要ERROR报警？

2020-09-21 07:23 UTC, xu-chaojie commented on src/client/libcurve_file.cpp
> +        LOG_IF(ERROR, ret != LIBCURVE_ERROR::OK)
GetFileInfo 失败这种情况是否包含 文件不存在的情况， 如果文件不存在那么不需要报警吧，查询一个不存在的文件应该是这个正常场景

2020-09-21 07:23 UTC, xu-chaojie commented on src/client/libcurve_file.cpp
>          ret = mdsClient_->Listdir(dirpath, userinfo, filestatVec);
同上，Listdir失败是否包含不存在的情况，不存在的情况下由于ERROR日志触发报警不合理

2020-09-21 07:23 UTC, xu-chaojie commented on src/client/libcurve_file.cpp
> +        LOG_IF(ERROR, ret != LIBCURVE_ERROR::OK)
Delete是否幂等，返回notexist之类的是否需要打error

2020-09-21 07:23 UTC, xu-chaojie commented on src/client/splitor.cpp
> +        if (re != LIBCURVE_ERROR::OK) {
如果是not exist 是否不需要报error而触发报警

2020-09-21 07:23 UTC, xu-chaojie commented on src/client/mds_client.cpp
> +        LOG_IF(WARNING, statusCode != 0)
这个文件统统改成warning是因为啥？

2020-09-21 11:18 UTC, wu-hanqing commented on src/client/chunk_closure.cpp
> +    LOG_EVERY_SECOND(WARNING) << OpTypeToString(reqCtx_->optype_)
这里只是一个rpc异常，比如超时，socket断开。但是后续会对请求进行重试，所以没必要ERROR

2020-09-21 11:21 UTC, wu-hanqing commented on src/client/libcurve_file.cpp
> +        LOG_IF(ERROR, ret != LIBCURVE_ERROR::OK)
这里提供的接口都是给上层的，比如qemu/nbd，挂在卷后，通过这个接口获取卷大小。所以这里正常不会出现文件不存在的情况。

2020-09-21 11:23 UTC, wu-hanqing commented on src/client/libcurve_file.cpp
> +        LOG_IF(ERROR, ret != LIBCURVE_ERROR::OK)
这里就涉及到幂等的问题了。即使这里不打印error，还是会返回给上层用户文件/目录已经被删除了。

2020-09-21 11:25 UTC, wu-hanqing commented on src/client/splitor.cpp
> +        if (re != LIBCURVE_ERROR::OK) {
这里的标志位true，所以不会返回not exist

2020-09-21 11:28 UTC, wu-hanqing commented on src/client/mds_client.cpp
> +        LOG_IF(WARNING, statusCode != 0)
mds client一侧只是与mds交互的逻辑，所以这里不需要对异常状态进行报错。
具体的报错应该由调用方根据返回的状态进行处理。

2020-09-21 11:33 UTC, wu-hanqing commented on src/client/libcurve_file.cpp
>          ret = mdsClient_->Listdir(dirpath, userinfo, filestatVec);
Done

2020-09-21 12:32 UTC, xu-chaojie approved these changes

2020-09-22 06:04 UTC, merged